#!/bin/bash
# Bootstrap script for backend setup
# Prompts for configuration and generates terraform.tfvars and backend.tf

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=========================================="
echo "Backend Setup Bootstrap"
echo "=========================================="
echo ""
echo "This script will configure the Terraform backend."
echo "You'll need to provide:"
echo "  - AWS Region"
echo "  - S3 Bucket Name (for state storage)"
echo "  - DynamoDB Table Name (for state locking)"
echo ""

# Prompt for values
read -p "AWS Region [us-east-1]: " AWS_REGION
AWS_REGION=${AWS_REGION:-us-east-1}

read -p "S3 Bucket Name: " BUCKET_NAME
if [ -z "$BUCKET_NAME" ]; then
    echo "Error: Bucket name is required"
    exit 1
fi

read -p "DynamoDB Table Name [terraform-state-lock]: " TABLE_NAME
TABLE_NAME=${TABLE_NAME:-terraform-state-lock}

echo ""
echo "Configuration:"
echo "  Region: $AWS_REGION"
echo "  Bucket: $BUCKET_NAME"
echo "  Table:  $TABLE_NAME"
echo ""
read -p "Proceed? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "Aborted."
    exit 0
fi

# Generate terraform.tfvars
cat > terraform.tfvars << EOF
aws_region         = "$AWS_REGION"
state_bucket_name  = "$BUCKET_NAME"
lock_table_name    = "$TABLE_NAME"
EOF

echo "✓ Created terraform.tfvars"

# Generate backend.tf.template (will be activated after resources exist)
cat > backend.tf.template << EOF
# Backend configuration for backend-setup module itself
# Auto-generated by bootstrap-backend.sh

terraform {
  backend "s3" {
    bucket         = "$BUCKET_NAME"
    key            = "rdsdb2-proxy/0-backend-setup/terraform.tfstate"
    region         = "$AWS_REGION"
    encrypt        = true
    dynamodb_table = "$TABLE_NAME"
  }
}
EOF

echo "✓ Created backend.tf.template"
echo "✓ Using local state initially (no backend.tf)"
echo ""
echo "=========================================="
echo "Bootstrap Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo ""
echo "  1. Initialize with local state:"
echo "     terraform init"
echo ""
echo "  2. Create backend resources:"
echo "     terraform apply -auto-approve"
echo ""
echo "  3. Migrate to remote state:"
echo "     mv backend.tf.template backend.tf"
echo "     terraform init -migrate-state"
echo ""
echo "  4. Configure other modules:"
echo "     ./configure-modules.sh"
echo ""
echo "  5. Deploy infrastructure:"
echo "     cd ../1-prerequisites"
echo "     terraform init"
echo "     terraform apply --auto-approve"
echo ""
