------------------------------------------------
-- DDL Statements for Table "MONITOR_START_TIME"
------------------------------------------------
 CREATE TABLE "MONITOR_START_TIME" ("MONITOR_START_TIME" TIMESTAMP NOT NULL);
------------------------------------------------
------------------------------------------------
-- DDL Statements for Table "MONITOR_END_TIME"
------------------------------------------------
 CREATE TABLE "MONITOR_END_TIME" ("MONITOR_END_TIME" TIMESTAMP NOT NULL);
------------------------------------------------
------------------------------------------------
-- DDL Statements for Table "DB_GET_CFG_START"
------------------------------------------------
 CREATE TABLE "DB_GET_CFG_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "NAME" VARCHAR(32), "VALUE" VARCHAR(1024), "VALUE_FLAGS" VARCHAR(10));
------------------------------------------------
-- DDL Statements for Table "DB_GET_CFG_END"
------------------------------------------------
 CREATE TABLE "DB_GET_CFG_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "NAME" VARCHAR(32), "VALUE" VARCHAR(1024), "VALUE_FLAGS" VARCHAR(10));
------------------------------------------------
-- DDL Statements for Table "DB_GET_CFG_DIFF"
------------------------------------------------
 CREATE TABLE "DB_GET_CFG_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "NAME" VARCHAR(32), "VALUE" VARCHAR(1024), "VALUE_FLAGS" VARCHAR(10));
------------------------------------------------
-- DDL Statements for Table "DBMCFG_START"
------------------------------------------------
 CREATE TABLE "DBMCFG_START" ("TS" TIMESTAMP NOT NULL, "NAME" VARCHAR(32), "VALUE" VARCHAR(1024), "VALUE_FLAGS" VARCHAR(10));
------------------------------------------------
-- DDL Statements for Table "DBMCFG_END"
------------------------------------------------
 CREATE TABLE "DBMCFG_END" ("TS" TIMESTAMP NOT NULL, "NAME" VARCHAR(32), "VALUE" VARCHAR(1024), "VALUE_FLAGS" VARCHAR(10));
------------------------------------------------
-- DDL Statements for Table "DBMCFG_DIFF"
------------------------------------------------
 CREATE TABLE "DBMCFG_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "NAME" VARCHAR(32), "VALUE" VARCHAR(1024), "VALUE_FLAGS" VARCHAR(10));
------------------------------------------------
-- DDL Statements for Table "ENV_CF_SYS_RESOURCES_START"
------------------------------------------------
 CREATE TABLE "ENV_CF_SYS_RESOURCES_START" ("TS" TIMESTAMP NOT NULL, "ID" SMALLINT , "NAME" VARCHAR(128), "VALUE" VARCHAR(1024), "UNIT" VARCHAR(128));
------------------------------------------------
-- DDL Statements for Table "ENV_CF_SYS_RESOURCES_END"
------------------------------------------------
 CREATE TABLE "ENV_CF_SYS_RESOURCES_END" ("TS" TIMESTAMP NOT NULL, "ID" SMALLINT , "NAME" VARCHAR(128), "VALUE" VARCHAR(1024), "UNIT" VARCHAR(128));
------------------------------------------------
-- DDL Statements for Table "ENV_CF_SYS_RESOURCES_DIFF"
------------------------------------------------
 CREATE TABLE "ENV_CF_SYS_RESOURCES_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "ID" SMALLINT , "NAME" VARCHAR(128), "VALUE" VARCHAR(1024), "UNIT" VARCHAR(128));
------------------------------------------------
-- DDL Statements for Table "ENV_GET_REG_VARIABLES_START"
------------------------------------------------
 CREATE TABLE "ENV_GET_REG_VARIABLES_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "REG_VAR_NAME" VARCHAR(256), "REG_VAR_VALUE" VARCHAR(2048), "LEVEL" CHAR(1));
------------------------------------------------
-- DDL Statements for Table "ENV_GET_REG_VARIABLES_END"
------------------------------------------------
 CREATE TABLE "ENV_GET_REG_VARIABLES_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "REG_VAR_NAME" VARCHAR(256), "REG_VAR_VALUE" VARCHAR(2048), "LEVEL" CHAR(1));
------------------------------------------------
-- DDL Statements for Table "ENV_GET_REG_VARIABLES_DIFF"
------------------------------------------------
 CREATE TABLE "ENV_GET_REG_VARIABLES_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "REG_VAR_NAME" VARCHAR(256), "REG_VAR_VALUE" VARCHAR(2048), "LEVEL" CHAR(1));
------------------------------------------------
-- DDL Statements for Table "ENV_GET_SYSTEM_RESOURCES_START"
------------------------------------------------
 CREATE TABLE "ENV_GET_SYSTEM_RESOURCES_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "OS_NAME" VARCHAR(256), "HOST_NAME" VARCHAR(255), "OS_VERSION" VARCHAR(256), "OS_RELEASE" VARCHAR(256), "CPU_TOTAL" BIGINT , "CPU_ONLINE" BIGINT , "CPU_CONFIGURED" BIGINT , "CPU_SPEED" BIGINT , "CPU_HMT_DEGREE" BIGINT , "MEMORY_TOTAL" BIGINT , "MEMORY_FREE" BIGINT , "CPU_LOAD_SHORT" DOUBLE, "CPU_LOAD_MEDIUM" DOUBLE, "CPU_LOAD_LONG" DOUBLE, "CPU_USAGE_TOTAL" SMALLINT , "SWAP_PAGES_IN" BIGINT , "SWAP_PAGES_OUT" BIGINT);
------------------------------------------------
-- DDL Statements for Table "ENV_GET_SYSTEM_RESOURCES_END"
------------------------------------------------
 CREATE TABLE "ENV_GET_SYSTEM_RESOURCES_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "OS_NAME" VARCHAR(256), "HOST_NAME" VARCHAR(255), "OS_VERSION" VARCHAR(256), "OS_RELEASE" VARCHAR(256), "CPU_TOTAL" BIGINT , "CPU_ONLINE" BIGINT , "CPU_CONFIGURED" BIGINT , "CPU_SPEED" BIGINT , "CPU_HMT_DEGREE" BIGINT , "MEMORY_TOTAL" BIGINT , "MEMORY_FREE" BIGINT , "CPU_LOAD_SHORT" DOUBLE, "CPU_LOAD_MEDIUM" DOUBLE, "CPU_LOAD_LONG" DOUBLE, "CPU_USAGE_TOTAL" SMALLINT , "SWAP_PAGES_IN" BIGINT , "SWAP_PAGES_OUT" BIGINT);
------------------------------------------------
-- DDL Statements for Table "ENV_GET_SYSTEM_RESOURCES_DIFF"
------------------------------------------------
 CREATE TABLE "ENV_GET_SYSTEM_RESOURCES_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "OS_NAME" VARCHAR(256), "HOST_NAME" VARCHAR(255), "OS_VERSION" VARCHAR(256), "OS_RELEASE" VARCHAR(256), "CPU_TOTAL" BIGINT , "CPU_ONLINE" BIGINT , "CPU_CONFIGURED" BIGINT , "CPU_SPEED" BIGINT , "CPU_HMT_DEGREE" BIGINT , "MEMORY_TOTAL" BIGINT , "MEMORY_FREE" BIGINT , "CPU_LOAD_SHORT" DOUBLE, "CPU_LOAD_MEDIUM" DOUBLE, "CPU_LOAD_LONG" DOUBLE, "CPU_USAGE_TOTAL" SMALLINT , "SWAP_PAGES_IN" BIGINT , "SWAP_PAGES_OUT" BIGINT);
------------------------------------------------
-- DDL Statements for Table "ENV_INST_INFO_START"
------------------------------------------------
 CREATE TABLE "ENV_INST_INFO_START" ("TS" TIMESTAMP NOT NULL, "INST_NAME" VARCHAR(128), "NUM_DBPARTITIONS" INTEGER , "SERVICE_LEVEL" VARCHAR(128), "BLD_LEVEL" VARCHAR(128), "PTF" VARCHAR(128), "NUM_MEMBERS" INTEGER);
------------------------------------------------
-- DDL Statements for Table "ENV_INST_INFO_END"
------------------------------------------------
 CREATE TABLE "ENV_INST_INFO_END" ("TS" TIMESTAMP NOT NULL, "INST_NAME" VARCHAR(128), "NUM_DBPARTITIONS" INTEGER , "SERVICE_LEVEL" VARCHAR(128), "BLD_LEVEL" VARCHAR(128), "PTF" VARCHAR(128), "NUM_MEMBERS" INTEGER);
------------------------------------------------
-- DDL Statements for Table "MON_GET_BUFFERPOOL_START"
------------------------------------------------
 CREATE TABLE "MON_GET_BUFFERPOOL_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "BP_NAME" VARCHAR(128), "BP_CUR_BUFFSZ" BIGINT , "AUTOMATIC" SMALLINT , "POOL_READ_TIME" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_ASYNC_READ_TIME" BIGINT , "POOL_ASYNC_DATA_READS" BIGINT , "POOL_ASYNC_INDEX_READS" BIGINT , "POOL_ASYNC_XDA_READS" BIGINT , "POOL_DATA_WRITES" BIGINT , "POOL_ASYNC_DATA_WRITES" BIGINT , "POOL_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_DATA_L_READS" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_INDEX_L_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_ASYNC_WRITE_TIME" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_ASYNC_INDEX_WRITES" BIGINT , "POOL_XDA_L_READS" BIGINT , "POOL_TEMP_XDA_L_READS" BIGINT , "POOL_XDA_P_READS" BIGINT , "POOL_TEMP_XDA_P_READS" BIGINT , "POOL_XDA_WRITES" BIGINT , "POOL_ASYNC_XDA_WRITES" BIGINT , "POOL_DATA_GBP_L_READS" BIGINT , "POOL_DATA_GBP_P_READS" BIGINT , "POOL_INDEX_GBP_L_READS" BIGINT , "POOL_INDEX_GBP_P_READS" BIGINT , "POOL_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_ASYNC_COL_READS" BIGINT , "POOL_COL_WRITES" BIGINT , "POOL_ASYNC_COL_WRITES" BIGINT , "POOL_COL_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_COL_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_COL_L_READS" BIGINT , "POOL_TEMP_COL_P_READS" BIGINT , "PAGESIZE" INTEGER NOT NULL);
------------------------------------------------
-- DDL Statements for Table "MON_GET_BUFFERPOOL_END"
------------------------------------------------
 CREATE TABLE "MON_GET_BUFFERPOOL_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "BP_NAME" VARCHAR(128), "BP_CUR_BUFFSZ" BIGINT , "AUTOMATIC" SMALLINT , "POOL_READ_TIME" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_ASYNC_READ_TIME" BIGINT , "POOL_ASYNC_DATA_READS" BIGINT , "POOL_ASYNC_INDEX_READS" BIGINT , "POOL_ASYNC_XDA_READS" BIGINT , "POOL_DATA_WRITES" BIGINT , "POOL_ASYNC_DATA_WRITES" BIGINT , "POOL_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_DATA_L_READS" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_INDEX_L_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_ASYNC_WRITE_TIME" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_ASYNC_INDEX_WRITES" BIGINT , "POOL_XDA_L_READS" BIGINT , "POOL_TEMP_XDA_L_READS" BIGINT , "POOL_XDA_P_READS" BIGINT , "POOL_TEMP_XDA_P_READS" BIGINT , "POOL_XDA_WRITES" BIGINT , "POOL_ASYNC_XDA_WRITES" BIGINT , "POOL_DATA_GBP_L_READS" BIGINT , "POOL_DATA_GBP_P_READS" BIGINT , "POOL_INDEX_GBP_L_READS" BIGINT , "POOL_INDEX_GBP_P_READS" BIGINT , "POOL_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_ASYNC_COL_READS" BIGINT , "POOL_COL_WRITES" BIGINT , "POOL_ASYNC_COL_WRITES" BIGINT , "POOL_COL_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_COL_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_COL_L_READS" BIGINT , "POOL_TEMP_COL_P_READS" BIGINT , "PAGESIZE" INTEGER NOT NULL);
------------------------------------------------
-- DDL Statements for Table "MON_GET_BUFFERPOOL_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_BUFFERPOOL_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "BP_NAME" VARCHAR(128), "BP_CUR_BUFFSZ" BIGINT , "AUTOMATIC" SMALLINT , "POOL_READ_TIME" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_ASYNC_READ_TIME" BIGINT , "POOL_ASYNC_DATA_READS" BIGINT , "POOL_ASYNC_INDEX_READS" BIGINT , "POOL_ASYNC_XDA_READS" BIGINT , "POOL_DATA_WRITES" BIGINT , "POOL_ASYNC_DATA_WRITES" BIGINT , "POOL_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_DATA_L_READS" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_INDEX_L_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_ASYNC_WRITE_TIME" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_ASYNC_INDEX_WRITES" BIGINT , "POOL_XDA_L_READS" BIGINT , "POOL_TEMP_XDA_L_READS" BIGINT , "POOL_XDA_P_READS" BIGINT , "POOL_TEMP_XDA_P_READS" BIGINT , "POOL_XDA_WRITES" BIGINT , "POOL_ASYNC_XDA_WRITES" BIGINT , "POOL_DATA_GBP_L_READS" BIGINT , "POOL_DATA_GBP_P_READS" BIGINT , "POOL_INDEX_GBP_L_READS" BIGINT , "POOL_INDEX_GBP_P_READS" BIGINT , "POOL_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_ASYNC_COL_READS" BIGINT , "POOL_COL_WRITES" BIGINT , "POOL_ASYNC_COL_WRITES" BIGINT , "POOL_COL_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_COL_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_COL_L_READS" BIGINT , "POOL_TEMP_COL_P_READS" BIGINT , "PAGESIZE" INTEGER NOT NULL);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CF_START"
------------------------------------------------
 CREATE TABLE "MON_GET_CF_START" ("TS" TIMESTAMP NOT NULL, "ID" SMALLINT , "HOST_NAME" VARCHAR(128), "CURRENT_CF_MEM_SIZE" INTEGER , "CONFIGURED_CF_MEM_SIZE" INTEGER , "CURRENT_CF_GBP_SIZE" INTEGER , "CONFIGURED_CF_GBP_SIZE" INTEGER , "TARGET_CF_GBP_SIZE" INTEGER , "CURRENT_CF_LOCK_SIZE" INTEGER , "CONFIGURED_CF_LOCK_SIZE" INTEGER , "TARGET_CF_LOCK_SIZE" INTEGER , "CURRENT_CF_SCA_SIZE" INTEGER , "CONFIGURED_CF_SCA_SIZE" INTEGER , "TARGET_CF_SCA_SIZE" INTEGER);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CF_END"
------------------------------------------------
 CREATE TABLE "MON_GET_CF_END" ("TS" TIMESTAMP NOT NULL, "ID" SMALLINT , "HOST_NAME" VARCHAR(128), "CURRENT_CF_MEM_SIZE" INTEGER , "CONFIGURED_CF_MEM_SIZE" INTEGER , "CURRENT_CF_GBP_SIZE" INTEGER , "CONFIGURED_CF_GBP_SIZE" INTEGER , "TARGET_CF_GBP_SIZE" INTEGER , "CURRENT_CF_LOCK_SIZE" INTEGER , "CONFIGURED_CF_LOCK_SIZE" INTEGER , "TARGET_CF_LOCK_SIZE" INTEGER , "CURRENT_CF_SCA_SIZE" INTEGER , "CONFIGURED_CF_SCA_SIZE" INTEGER , "TARGET_CF_SCA_SIZE" INTEGER);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CF_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_CF_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "ID" SMALLINT , "HOST_NAME" VARCHAR(128), "CURRENT_CF_MEM_SIZE" INTEGER , "CONFIGURED_CF_MEM_SIZE" INTEGER , "CURRENT_CF_GBP_SIZE" INTEGER , "CONFIGURED_CF_GBP_SIZE" INTEGER , "TARGET_CF_GBP_SIZE" INTEGER , "CURRENT_CF_LOCK_SIZE" INTEGER , "CONFIGURED_CF_LOCK_SIZE" INTEGER , "TARGET_CF_LOCK_SIZE" INTEGER , "CURRENT_CF_SCA_SIZE" INTEGER , "CONFIGURED_CF_SCA_SIZE" INTEGER , "TARGET_CF_SCA_SIZE" INTEGER);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CF_CMD_START"
------------------------------------------------
 CREATE TABLE "MON_GET_CF_CMD_START" ("TS" TIMESTAMP NOT NULL, "HOSTNAME" VARCHAR(255), "ID" SMALLINT , "CF_CMD_NAME" VARCHAR(128), "TOTAL_CF_REQUESTS" BIGINT , "TOTAL_CF_CMD_TIME_MICRO" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CF_CMD_END"
------------------------------------------------
 CREATE TABLE "MON_GET_CF_CMD_END" ("TS" TIMESTAMP NOT NULL, "HOSTNAME" VARCHAR(255), "ID" SMALLINT , "CF_CMD_NAME" VARCHAR(128), "TOTAL_CF_REQUESTS" BIGINT , "TOTAL_CF_CMD_TIME_MICRO" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CF_CMD_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_CF_CMD_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "HOSTNAME" VARCHAR(255), "ID" SMALLINT , "CF_CMD_NAME" VARCHAR(128), "TOTAL_CF_REQUESTS" BIGINT , "TOTAL_CF_CMD_TIME_MICRO" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CF_WAIT_TIME_START"
------------------------------------------------
 CREATE TABLE "MON_GET_CF_WAIT_TIME_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "HOSTNAME" VARCHAR(255), "ID" SMALLINT , "CF_CMD_NAME" VARCHAR(128), "TOTAL_CF_REQUESTS" BIGINT , "TOTAL_CF_WAIT_TIME_MICRO" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CF_WAIT_TIME_END"
------------------------------------------------
 CREATE TABLE "MON_GET_CF_WAIT_TIME_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "HOSTNAME" VARCHAR(255), "ID" SMALLINT , "CF_CMD_NAME" VARCHAR(128), "TOTAL_CF_REQUESTS" BIGINT , "TOTAL_CF_WAIT_TIME_MICRO" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CF_WAIT_TIME_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_CF_WAIT_TIME_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "HOSTNAME" VARCHAR(255), "ID" SMALLINT , "CF_CMD_NAME" VARCHAR(128), "TOTAL_CF_REQUESTS" BIGINT , "TOTAL_CF_WAIT_TIME_MICRO" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CONNECTION_START"
------------------------------------------------
 CREATE TABLE "MON_GET_CONNECTION_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "APPLICATION_NAME" VARCHAR(128), "APPLICATION_HANDLE" BIGINT , "CLIENT_APPLNAME" VARCHAR(255), "CONNECTION_REUSABILITY_STATUS" SMALLINT , "REUSABILITY_STATUS_REASON" VARCHAR(255), "CLIENT_IDLE_WAIT_TIME" BIGINT , "TOTAL_RQST_TIME" BIGINT , "RQSTS_COMPLETED_TOTAL" BIGINT , "TOTAL_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "TOTAL_SECTION_SORT_TIME" BIGINT , "TOTAL_COMMIT_TIME" BIGINT , "TOTAL_RUNSTATS_TIME" BIGINT , "TOTAL_REORG_TIME" BIGINT , "TOTAL_LOAD_TIME" BIGINT , "TOTAL_APP_COMMITS" BIGINT , "TOTAL_APP_ROLLBACKS" BIGINT , "DEADLOCKS" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "TOTAL_SORTS" BIGINT , "TOTAL_REORGS" BIGINT , "TOTAL_LOADS" BIGINT , "TOTAL_RUNSTATS" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "IDA_SEND_WAIT_TIME" BIGINT , "IDA_RECV_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "DIAGLOG_WRITE_WAIT_TIME" BIGINT , "LOG_BUFFER_WAIT_TIME" BIGINT , "AUDIT_FILE_WRITE_WAIT_TIME" BIGINT , "AUDIT_SUBSYSTEM_WAIT_TIME" BIGINT , "FCM_MESSAGE_RECV_WAIT_TIME" BIGINT , "FCM_MESSAGE_SEND_WAIT_TIME" BIGINT , "FCM_TQ_RECV_WAIT_TIME" BIGINT , "FCM_TQ_SEND_WAIT_TIME" BIGINT , "EVMON_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME_GLOBAL" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "COMM_EXIT_WAIT_TIME" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "LOB_PREFETCH_WAIT_TIME" BIGINT , "FED_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CONNECTION_END"
------------------------------------------------
 CREATE TABLE "MON_GET_CONNECTION_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "APPLICATION_NAME" VARCHAR(128), "APPLICATION_HANDLE" BIGINT , "CLIENT_APPLNAME" VARCHAR(255), "CONNECTION_REUSABILITY_STATUS" SMALLINT , "REUSABILITY_STATUS_REASON" VARCHAR(255), "CLIENT_IDLE_WAIT_TIME" BIGINT , "TOTAL_RQST_TIME" BIGINT , "RQSTS_COMPLETED_TOTAL" BIGINT , "TOTAL_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "TOTAL_SECTION_SORT_TIME" BIGINT , "TOTAL_COMMIT_TIME" BIGINT , "TOTAL_RUNSTATS_TIME" BIGINT , "TOTAL_REORG_TIME" BIGINT , "TOTAL_LOAD_TIME" BIGINT , "TOTAL_APP_COMMITS" BIGINT , "TOTAL_APP_ROLLBACKS" BIGINT , "DEADLOCKS" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "TOTAL_SORTS" BIGINT , "TOTAL_REORGS" BIGINT , "TOTAL_LOADS" BIGINT , "TOTAL_RUNSTATS" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "IDA_SEND_WAIT_TIME" BIGINT , "IDA_RECV_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "DIAGLOG_WRITE_WAIT_TIME" BIGINT , "LOG_BUFFER_WAIT_TIME" BIGINT , "AUDIT_FILE_WRITE_WAIT_TIME" BIGINT , "AUDIT_SUBSYSTEM_WAIT_TIME" BIGINT , "FCM_MESSAGE_RECV_WAIT_TIME" BIGINT , "FCM_MESSAGE_SEND_WAIT_TIME" BIGINT , "FCM_TQ_RECV_WAIT_TIME" BIGINT , "FCM_TQ_SEND_WAIT_TIME" BIGINT , "EVMON_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME_GLOBAL" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "COMM_EXIT_WAIT_TIME" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "LOB_PREFETCH_WAIT_TIME" BIGINT , "FED_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_CONNECTION_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_CONNECTION_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "APPLICATION_NAME" VARCHAR(128), "APPLICATION_HANDLE" BIGINT , "CLIENT_APPLNAME" VARCHAR(255), "CONNECTION_REUSABILITY_STATUS" SMALLINT , "REUSABILITY_STATUS_REASON" VARCHAR(255), "CLIENT_IDLE_WAIT_TIME" BIGINT , "TOTAL_RQST_TIME" BIGINT , "RQSTS_COMPLETED_TOTAL" BIGINT , "TOTAL_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "TOTAL_SECTION_SORT_TIME" BIGINT , "TOTAL_COMMIT_TIME" BIGINT , "TOTAL_RUNSTATS_TIME" BIGINT , "TOTAL_REORG_TIME" BIGINT , "TOTAL_LOAD_TIME" BIGINT , "TOTAL_APP_COMMITS" BIGINT , "TOTAL_APP_ROLLBACKS" BIGINT , "DEADLOCKS" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "TOTAL_SORTS" BIGINT , "TOTAL_REORGS" BIGINT , "TOTAL_LOADS" BIGINT , "TOTAL_RUNSTATS" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "IDA_SEND_WAIT_TIME" BIGINT , "IDA_RECV_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "DIAGLOG_WRITE_WAIT_TIME" BIGINT , "LOG_BUFFER_WAIT_TIME" BIGINT , "AUDIT_FILE_WRITE_WAIT_TIME" BIGINT , "AUDIT_SUBSYSTEM_WAIT_TIME" BIGINT , "FCM_MESSAGE_RECV_WAIT_TIME" BIGINT , "FCM_MESSAGE_SEND_WAIT_TIME" BIGINT , "FCM_TQ_RECV_WAIT_TIME" BIGINT , "FCM_TQ_SEND_WAIT_TIME" BIGINT , "EVMON_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME_GLOBAL" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "COMM_EXIT_WAIT_TIME" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "LOB_PREFETCH_WAIT_TIME" BIGINT , "FED_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_EXTENDED_LATCH_WAIT_START"
------------------------------------------------
 CREATE TABLE "MON_GET_EXTENDED_LATCH_WAIT_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "LATCH_NAME" VARCHAR(256), "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAITS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_EXTENDED_LATCH_WAIT_END"
------------------------------------------------
 CREATE TABLE "MON_GET_EXTENDED_LATCH_WAIT_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "LATCH_NAME" VARCHAR(256), "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAITS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_EXTENDED_LATCH_WAIT_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_EXTENDED_LATCH_WAIT_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "LATCH_NAME" VARCHAR(256), "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAITS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_GROUP_BUFFERPOOL_START"
------------------------------------------------
 CREATE TABLE "MON_GET_GROUP_BUFFERPOOL_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "NUM_GBP_FULL" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_GROUP_BUFFERPOOL_END"
------------------------------------------------
 CREATE TABLE "MON_GET_GROUP_BUFFERPOOL_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "NUM_GBP_FULL" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_GROUP_BUFFERPOOL_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_GROUP_BUFFERPOOL_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "NUM_GBP_FULL" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_INDEX_START"
------------------------------------------------
 CREATE TABLE "MON_GET_INDEX_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TABSCHEMA" VARCHAR(128), "TABNAME" VARCHAR(128), "IID" SMALLINT , "DATA_PARTITION_ID" INTEGER , "NLEAF" BIGINT , "NLEVELS" SMALLINT , "INDEX_SCANS" BIGINT , "INDEX_ONLY_SCANS" BIGINT , "KEY_UPDATES" BIGINT , "INCLUDE_COL_UPDATES" BIGINT , "PSEUDO_DELETES" BIGINT , "DEL_KEYS_CLEANED" BIGINT , "ROOT_NODE_SPLITS" BIGINT , "INT_NODE_SPLITS" BIGINT , "BOUNDARY_LEAF_NODE_SPLITS" BIGINT , "NONBOUNDARY_LEAF_NODE_SPLITS" BIGINT , "PAGE_ALLOCATIONS" BIGINT , "PSEUDO_EMPTY_PAGES" BIGINT , "EMPTY_PAGES_REUSED" BIGINT , "EMPTY_PAGES_DELETED" BIGINT , "PAGES_MERGED" BIGINT , "OBJECT_INDEX_L_READS" BIGINT , "OBJECT_INDEX_P_READS" BIGINT , "OBJECT_INDEX_GBP_L_READS" BIGINT , "OBJECT_INDEX_GBP_P_READS" BIGINT , "OBJECT_INDEX_GBP_INVALID_PAGES" BIGINT , "OBJECT_INDEX_LBP_PAGES_FOUND" BIGINT , "OBJECT_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT , "INDEX_JUMP_SCANS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_INDEX_END"
------------------------------------------------
 CREATE TABLE "MON_GET_INDEX_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TABSCHEMA" VARCHAR(128), "TABNAME" VARCHAR(128), "IID" SMALLINT , "DATA_PARTITION_ID" INTEGER , "NLEAF" BIGINT , "NLEVELS" SMALLINT , "INDEX_SCANS" BIGINT , "INDEX_ONLY_SCANS" BIGINT , "KEY_UPDATES" BIGINT , "INCLUDE_COL_UPDATES" BIGINT , "PSEUDO_DELETES" BIGINT , "DEL_KEYS_CLEANED" BIGINT , "ROOT_NODE_SPLITS" BIGINT , "INT_NODE_SPLITS" BIGINT , "BOUNDARY_LEAF_NODE_SPLITS" BIGINT , "NONBOUNDARY_LEAF_NODE_SPLITS" BIGINT , "PAGE_ALLOCATIONS" BIGINT , "PSEUDO_EMPTY_PAGES" BIGINT , "EMPTY_PAGES_REUSED" BIGINT , "EMPTY_PAGES_DELETED" BIGINT , "PAGES_MERGED" BIGINT , "OBJECT_INDEX_L_READS" BIGINT , "OBJECT_INDEX_P_READS" BIGINT , "OBJECT_INDEX_GBP_L_READS" BIGINT , "OBJECT_INDEX_GBP_P_READS" BIGINT , "OBJECT_INDEX_GBP_INVALID_PAGES" BIGINT , "OBJECT_INDEX_LBP_PAGES_FOUND" BIGINT , "OBJECT_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT , "INDEX_JUMP_SCANS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_INDEX_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_INDEX_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TABSCHEMA" VARCHAR(128), "TABNAME" VARCHAR(128), "IID" SMALLINT , "DATA_PARTITION_ID" INTEGER , "NLEAF" BIGINT , "NLEVELS" SMALLINT , "INDEX_SCANS" BIGINT , "INDEX_ONLY_SCANS" BIGINT , "KEY_UPDATES" BIGINT , "INCLUDE_COL_UPDATES" BIGINT , "PSEUDO_DELETES" BIGINT , "DEL_KEYS_CLEANED" BIGINT , "ROOT_NODE_SPLITS" BIGINT , "INT_NODE_SPLITS" BIGINT , "BOUNDARY_LEAF_NODE_SPLITS" BIGINT , "NONBOUNDARY_LEAF_NODE_SPLITS" BIGINT , "PAGE_ALLOCATIONS" BIGINT , "PSEUDO_EMPTY_PAGES" BIGINT , "EMPTY_PAGES_REUSED" BIGINT , "EMPTY_PAGES_DELETED" BIGINT , "PAGES_MERGED" BIGINT , "OBJECT_INDEX_L_READS" BIGINT , "OBJECT_INDEX_P_READS" BIGINT , "OBJECT_INDEX_GBP_L_READS" BIGINT , "OBJECT_INDEX_GBP_P_READS" BIGINT , "OBJECT_INDEX_GBP_INVALID_PAGES" BIGINT , "OBJECT_INDEX_LBP_PAGES_FOUND" BIGINT , "OBJECT_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT , "INDEX_JUMP_SCANS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_MEMORY_POOL_START"
------------------------------------------------
 CREATE TABLE "MON_GET_MEMORY_POOL_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "MEMORY_POOL_TYPE" VARCHAR(32), "DB_NAME" VARCHAR(128), "MEMORY_POOL_USED" BIGINT , "MEMORY_POOL_USED_HWM" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_MEMORY_POOL_END"
------------------------------------------------
 CREATE TABLE "MON_GET_MEMORY_POOL_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "MEMORY_POOL_TYPE" VARCHAR(32), "DB_NAME" VARCHAR(128), "MEMORY_POOL_USED" BIGINT , "MEMORY_POOL_USED_HWM" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_MEMORY_POOL_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_MEMORY_POOL_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "MEMORY_POOL_TYPE" VARCHAR(32), "DB_NAME" VARCHAR(128), "MEMORY_POOL_USED" BIGINT , "MEMORY_POOL_USED_HWM" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_MEMORY_SET_START"
------------------------------------------------
 CREATE TABLE "MON_GET_MEMORY_SET_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "MEMORY_SET_TYPE" VARCHAR(32), "DB_NAME" VARCHAR(128), "MEMORY_SET_USED" BIGINT , "MEMORY_SET_USED_HWM" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_MEMORY_SET_END"
------------------------------------------------
 CREATE TABLE "MON_GET_MEMORY_SET_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "MEMORY_SET_TYPE" VARCHAR(32), "DB_NAME" VARCHAR(128), "MEMORY_SET_USED" BIGINT , "MEMORY_SET_USED_HWM" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_MEMORY_SET_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_MEMORY_SET_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "MEMORY_SET_TYPE" VARCHAR(32), "DB_NAME" VARCHAR(128), "MEMORY_SET_USED" BIGINT , "MEMORY_SET_USED_HWM" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_PAGE_ACCESS_INFO_START"
------------------------------------------------
 CREATE TABLE "MON_GET_PAGE_ACCESS_INFO_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TABSCHEMA" VARCHAR(128), "TABNAME" VARCHAR(128), "OBJTYPE" VARCHAR(128), "DATA_PARTITION_ID" INTEGER , "IID" SMALLINT , "PAGE_RECLAIMS_X" BIGINT , "PAGE_RECLAIMS_S" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "SPACEMAPPAGE_PAGE_RECLAIMS_X" BIGINT , "SPACEMAPPAGE_PAGE_RECLAIMS_S" BIGINT , "SPACEMAPPAGE_RECLAIM_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_PAGE_ACCESS_INFO_END"
------------------------------------------------
 CREATE TABLE "MON_GET_PAGE_ACCESS_INFO_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TABSCHEMA" VARCHAR(128), "TABNAME" VARCHAR(128), "OBJTYPE" VARCHAR(128), "DATA_PARTITION_ID" INTEGER , "IID" SMALLINT , "PAGE_RECLAIMS_X" BIGINT , "PAGE_RECLAIMS_S" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "SPACEMAPPAGE_PAGE_RECLAIMS_X" BIGINT , "SPACEMAPPAGE_PAGE_RECLAIMS_S" BIGINT , "SPACEMAPPAGE_RECLAIM_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_PAGE_ACCESS_INFO_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_PAGE_ACCESS_INFO_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TABSCHEMA" VARCHAR(128), "TABNAME" VARCHAR(128), "OBJTYPE" VARCHAR(128), "DATA_PARTITION_ID" INTEGER , "IID" SMALLINT , "PAGE_RECLAIMS_X" BIGINT , "PAGE_RECLAIMS_S" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "SPACEMAPPAGE_PAGE_RECLAIMS_X" BIGINT , "SPACEMAPPAGE_PAGE_RECLAIMS_S" BIGINT , "SPACEMAPPAGE_RECLAIM_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_PKG_CACHE_STMT_START"
------------------------------------------------
 CREATE TABLE "MON_GET_PKG_CACHE_STMT_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "PLANID" BIGINT , "EXECUTABLE_ID" VARCHAR(32), "PACKAGE_NAME" VARCHAR(128), "STMT_TEXT" CLOB(2097152), "EFFECTIVE_ISOLATION" CHAR(2), "STMTID" BIGINT , "SEMANTIC_ENV_ID" BIGINT , "ACTIVE_SORTS_TOP" BIGINT , "SORT_HEAP_TOP" BIGINT , "SORT_SHRHEAP_TOP" BIGINT , "NUM_EXEC_WITH_METRICS" BIGINT , "COORD_STMT_EXEC_TIME" BIGINT , "TOTAL_ACT_TIME" BIGINT , "TOTAL_CPU_TIME" BIGINT , "TOTAL_ACT_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "LOG_BUFFER_WAIT_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "TOTAL_SORTS" BIGINT , "SORT_OVERFLOWS" BIGINT , "TOTAL_SECTION_TIME" BIGINT , "TOTAL_SECTION_SORT_TIME" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_DATA_WRITES" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "DIRECT_READ_REQS" BIGINT , "DIRECT_WRITE_REQS" BIGINT , "IDA_SEND_WAIT_TIME" BIGINT , "IDA_RECV_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME_GLOBAL" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "DIAGLOG_WRITE_WAIT_TIME" BIGINT , "AUDIT_FILE_WRITE_WAIT_TIME" BIGINT , "AUDIT_SUBSYSTEM_WAIT_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "FCM_MESSAGE_RECV_WAIT_TIME" BIGINT , "FCM_MESSAGE_SEND_WAIT_TIME" BIGINT , "FCM_TQ_RECV_WAIT_TIME" BIGINT , "FCM_TQ_SEND_WAIT_TIME" BIGINT , "EVMON_WAIT_TIME" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "TOTAL_COL_TIME" BIGINT , "COMM_EXIT_WAIT_TIME" BIGINT , "COL_SYNOPSIS_ROWS_INSERTED" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "LOB_PREFETCH_WAIT_TIME" BIGINT , "FED_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_PKG_CACHE_STMT_END"
------------------------------------------------
 CREATE TABLE "MON_GET_PKG_CACHE_STMT_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "PLANID" BIGINT , "EXECUTABLE_ID" VARCHAR(32), "PACKAGE_NAME" VARCHAR(128), "STMT_TEXT" CLOB(2097152), "EFFECTIVE_ISOLATION" CHAR(2), "STMTID" BIGINT , "SEMANTIC_ENV_ID" BIGINT , "ACTIVE_SORTS_TOP" BIGINT , "SORT_HEAP_TOP" BIGINT , "SORT_SHRHEAP_TOP" BIGINT , "NUM_EXEC_WITH_METRICS" BIGINT , "COORD_STMT_EXEC_TIME" BIGINT , "TOTAL_ACT_TIME" BIGINT , "TOTAL_CPU_TIME" BIGINT , "TOTAL_ACT_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "LOG_BUFFER_WAIT_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "TOTAL_SORTS" BIGINT , "SORT_OVERFLOWS" BIGINT , "TOTAL_SECTION_TIME" BIGINT , "TOTAL_SECTION_SORT_TIME" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_DATA_WRITES" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "DIRECT_READ_REQS" BIGINT , "DIRECT_WRITE_REQS" BIGINT , "IDA_SEND_WAIT_TIME" BIGINT , "IDA_RECV_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME_GLOBAL" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "DIAGLOG_WRITE_WAIT_TIME" BIGINT , "AUDIT_FILE_WRITE_WAIT_TIME" BIGINT , "AUDIT_SUBSYSTEM_WAIT_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "FCM_MESSAGE_RECV_WAIT_TIME" BIGINT , "FCM_MESSAGE_SEND_WAIT_TIME" BIGINT , "FCM_TQ_RECV_WAIT_TIME" BIGINT , "FCM_TQ_SEND_WAIT_TIME" BIGINT , "EVMON_WAIT_TIME" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "TOTAL_COL_TIME" BIGINT , "COMM_EXIT_WAIT_TIME" BIGINT , "COL_SYNOPSIS_ROWS_INSERTED" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "LOB_PREFETCH_WAIT_TIME" BIGINT , "FED_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_PKG_CACHE_STMT_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_PKG_CACHE_STMT_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "PLANID" BIGINT , "EXECUTABLE_ID" VARCHAR(32), "PACKAGE_NAME" VARCHAR(128), "STMT_TEXT" CLOB(2097152), "EFFECTIVE_ISOLATION" CHAR(2), "STMTID" BIGINT , "SEMANTIC_ENV_ID" BIGINT , "ACTIVE_SORTS_TOP" BIGINT , "SORT_HEAP_TOP" BIGINT , "SORT_SHRHEAP_TOP" BIGINT , "NUM_EXEC_WITH_METRICS" BIGINT , "COORD_STMT_EXEC_TIME" BIGINT , "TOTAL_ACT_TIME" BIGINT , "TOTAL_CPU_TIME" BIGINT , "TOTAL_ACT_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "LOG_BUFFER_WAIT_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "TOTAL_SORTS" BIGINT , "SORT_OVERFLOWS" BIGINT , "TOTAL_SECTION_TIME" BIGINT , "TOTAL_SECTION_SORT_TIME" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_DATA_WRITES" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "DIRECT_READ_REQS" BIGINT , "DIRECT_WRITE_REQS" BIGINT , "IDA_SEND_WAIT_TIME" BIGINT , "IDA_RECV_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME_GLOBAL" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "DIAGLOG_WRITE_WAIT_TIME" BIGINT , "AUDIT_FILE_WRITE_WAIT_TIME" BIGINT , "AUDIT_SUBSYSTEM_WAIT_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "FCM_MESSAGE_RECV_WAIT_TIME" BIGINT , "FCM_MESSAGE_SEND_WAIT_TIME" BIGINT , "FCM_TQ_RECV_WAIT_TIME" BIGINT , "FCM_TQ_SEND_WAIT_TIME" BIGINT , "EVMON_WAIT_TIME" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "TOTAL_COL_TIME" BIGINT , "COMM_EXIT_WAIT_TIME" BIGINT , "COL_SYNOPSIS_ROWS_INSERTED" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "LOB_PREFETCH_WAIT_TIME" BIGINT , "FED_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_SERVERLIST_START"
------------------------------------------------
 CREATE TABLE "MON_GET_SERVERLIST_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "CACHED_TIMESTAMP" TIMESTAMP , "HOSTNAME" VARCHAR(255), "PORT_NUMBER" INTEGER , "SSL_PORT_NUMBER" INTEGER , "PRIORITY" SMALLINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_SERVERLIST_END"
------------------------------------------------
 CREATE TABLE "MON_GET_SERVERLIST_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "CACHED_TIMESTAMP" TIMESTAMP , "HOSTNAME" VARCHAR(255), "PORT_NUMBER" INTEGER , "SSL_PORT_NUMBER" INTEGER , "PRIORITY" SMALLINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_SERVERLIST_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_SERVERLIST_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "CACHED_TIMESTAMP" TIMESTAMP , "HOSTNAME" VARCHAR(255), "PORT_NUMBER" INTEGER , "SSL_PORT_NUMBER" INTEGER , "PRIORITY" SMALLINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_TABLE_START"
------------------------------------------------
 CREATE TABLE "MON_GET_TABLE_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TABNAME" VARCHAR(128), "TABSCHEMA" VARCHAR(128), "DATA_PARTITION_ID" INTEGER , "TBSP_ID" BIGINT , "TAB_FILE_ID" BIGINT , "DATA_SHARING_STATE_CHANGE_TIME" TIMESTAMP , "DATA_SHARING_STATE" VARCHAR(19), "ROWS_READ" BIGINT , "ROWS_INSERTED" BIGINT , "ROWS_UPDATED" BIGINT , "ROWS_DELETED" BIGINT , "OVERFLOW_ACCESSES" BIGINT , "OVERFLOW_CREATES" BIGINT , "PAGE_REORGS" BIGINT , "DIRECT_READ_REQS" BIGINT , "DIRECT_WRITE_REQS" BIGINT , "OBJECT_DATA_P_READS" BIGINT , "OBJECT_DATA_L_READS" BIGINT , "DATA_SHARING_REMOTE_LOCKWAIT_COUNT" BIGINT , "DATA_SHARING_REMOTE_LOCKWAIT_TIME" BIGINT , "COL_OBJECT_L_PAGES" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_TABLE_END"
------------------------------------------------
 CREATE TABLE "MON_GET_TABLE_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TABNAME" VARCHAR(128), "TABSCHEMA" VARCHAR(128), "DATA_PARTITION_ID" INTEGER , "TBSP_ID" BIGINT , "TAB_FILE_ID" BIGINT , "DATA_SHARING_STATE_CHANGE_TIME" TIMESTAMP , "DATA_SHARING_STATE" VARCHAR(19), "ROWS_READ" BIGINT , "ROWS_INSERTED" BIGINT , "ROWS_UPDATED" BIGINT , "ROWS_DELETED" BIGINT , "OVERFLOW_ACCESSES" BIGINT , "OVERFLOW_CREATES" BIGINT , "PAGE_REORGS" BIGINT , "DIRECT_READ_REQS" BIGINT , "DIRECT_WRITE_REQS" BIGINT , "OBJECT_DATA_P_READS" BIGINT , "OBJECT_DATA_L_READS" BIGINT , "DATA_SHARING_REMOTE_LOCKWAIT_COUNT" BIGINT , "DATA_SHARING_REMOTE_LOCKWAIT_TIME" BIGINT , "COL_OBJECT_L_PAGES" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_TABLE_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_TABLE_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TABNAME" VARCHAR(128), "TABSCHEMA" VARCHAR(128), "DATA_PARTITION_ID" INTEGER , "TBSP_ID" BIGINT , "TAB_FILE_ID" BIGINT , "DATA_SHARING_STATE_CHANGE_TIME" TIMESTAMP , "DATA_SHARING_STATE" VARCHAR(19), "ROWS_READ" BIGINT , "ROWS_INSERTED" BIGINT , "ROWS_UPDATED" BIGINT , "ROWS_DELETED" BIGINT , "OVERFLOW_ACCESSES" BIGINT , "OVERFLOW_CREATES" BIGINT , "PAGE_REORGS" BIGINT , "DIRECT_READ_REQS" BIGINT , "DIRECT_WRITE_REQS" BIGINT , "OBJECT_DATA_P_READS" BIGINT , "OBJECT_DATA_L_READS" BIGINT , "DATA_SHARING_REMOTE_LOCKWAIT_COUNT" BIGINT , "DATA_SHARING_REMOTE_LOCKWAIT_TIME" BIGINT , "COL_OBJECT_L_PAGES" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_TABLESPACE_START"
------------------------------------------------
 CREATE TABLE "MON_GET_TABLESPACE_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(128), "TBSP_PAGE_SIZE" BIGINT , "TBSP_ID" BIGINT , "TBSP_EXTENT_SIZE" BIGINT , "TBSP_PREFETCH_SIZE" BIGINT , "FS_CACHING" SMALLINT , "POOL_READ_TIME" BIGINT , "POOL_ASYNC_READ_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_ASYNC_WRITE_TIME" BIGINT , "POOL_DATA_WRITES" BIGINT , "POOL_ASYNC_DATA_WRITES" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_ASYNC_INDEX_WRITES" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_TEMP_DATA_L_READS" BIGINT , "POOL_ASYNC_DATA_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_ASYNC_INDEX_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_TEMP_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "POOL_XDA_L_READS" BIGINT , "POOL_TEMP_XDA_L_READS" BIGINT , "POOL_ASYNC_XDA_READS" BIGINT , "POOL_XDA_P_READS" BIGINT , "POOL_TEMP_XDA_P_READS" BIGINT , "POOL_XDA_WRITES" BIGINT , "POOL_ASYNC_XDA_WRITES" BIGINT , "UNREAD_PREFETCH_PAGES" BIGINT , "VECTORED_IOS" BIGINT , "PAGES_FROM_VECTORED_IOS" BIGINT , "BLOCK_IOS" BIGINT , "PAGES_FROM_BLOCK_IOS" BIGINT , "POOL_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_INDEX_LBP_PAGES_FOUND" BIGINT , "DIRECT_READ_REQS" BIGINT , "DIRECT_WRITE_REQS" BIGINT , "DIRECT_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "TBSP_USED_PAGES" BIGINT , "TBSP_PAGE_TOP" BIGINT , "POOL_DATA_GBP_L_READS" BIGINT , "POOL_DATA_GBP_P_READS" BIGINT , "POOL_INDEX_GBP_L_READS" BIGINT , "POOL_INDEX_GBP_P_READS" BIGINT , "POOL_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_L_READS" BIGINT , "POOL_ASYNC_DATA_GBP_P_READS" BIGINT , "POOL_ASYNC_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT , "POOL_ASYNC_INDEX_GBP_L_READS" BIGINT , "POOL_ASYNC_INDEX_GBP_P_READS" BIGINT , "POOL_ASYNC_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "PREFETCH_WAITS" BIGINT , "SKIPPED_PREFETCH_DATA_P_READS" BIGINT , "SKIPPED_PREFETCH_INDEX_P_READS" BIGINT , "SKIPPED_PREFETCH_TEMP_DATA_P_READS" BIGINT , "SKIPPED_PREFETCH_TEMP_INDEX_P_READS" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_ASYNC_COL_READS" BIGINT , "POOL_COL_WRITES" BIGINT , "POOL_ASYNC_COL_WRITES" BIGINT , "POOL_COL_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_COL_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_COL_L_READS" BIGINT , "POOL_TEMP_COL_P_READS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_TABLESPACE_END"
------------------------------------------------
 CREATE TABLE "MON_GET_TABLESPACE_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(128), "TBSP_PAGE_SIZE" BIGINT , "TBSP_ID" BIGINT , "TBSP_EXTENT_SIZE" BIGINT , "TBSP_PREFETCH_SIZE" BIGINT , "FS_CACHING" SMALLINT , "POOL_READ_TIME" BIGINT , "POOL_ASYNC_READ_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_ASYNC_WRITE_TIME" BIGINT , "POOL_DATA_WRITES" BIGINT , "POOL_ASYNC_DATA_WRITES" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_ASYNC_INDEX_WRITES" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_TEMP_DATA_L_READS" BIGINT , "POOL_ASYNC_DATA_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_ASYNC_INDEX_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_TEMP_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "POOL_XDA_L_READS" BIGINT , "POOL_TEMP_XDA_L_READS" BIGINT , "POOL_ASYNC_XDA_READS" BIGINT , "POOL_XDA_P_READS" BIGINT , "POOL_TEMP_XDA_P_READS" BIGINT , "POOL_XDA_WRITES" BIGINT , "POOL_ASYNC_XDA_WRITES" BIGINT , "UNREAD_PREFETCH_PAGES" BIGINT , "VECTORED_IOS" BIGINT , "PAGES_FROM_VECTORED_IOS" BIGINT , "BLOCK_IOS" BIGINT , "PAGES_FROM_BLOCK_IOS" BIGINT , "POOL_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_INDEX_LBP_PAGES_FOUND" BIGINT , "DIRECT_READ_REQS" BIGINT , "DIRECT_WRITE_REQS" BIGINT , "DIRECT_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "TBSP_USED_PAGES" BIGINT , "TBSP_PAGE_TOP" BIGINT , "POOL_DATA_GBP_L_READS" BIGINT , "POOL_DATA_GBP_P_READS" BIGINT , "POOL_INDEX_GBP_L_READS" BIGINT , "POOL_INDEX_GBP_P_READS" BIGINT , "POOL_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_L_READS" BIGINT , "POOL_ASYNC_DATA_GBP_P_READS" BIGINT , "POOL_ASYNC_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT , "POOL_ASYNC_INDEX_GBP_L_READS" BIGINT , "POOL_ASYNC_INDEX_GBP_P_READS" BIGINT , "POOL_ASYNC_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "PREFETCH_WAITS" BIGINT , "SKIPPED_PREFETCH_DATA_P_READS" BIGINT , "SKIPPED_PREFETCH_INDEX_P_READS" BIGINT , "SKIPPED_PREFETCH_TEMP_DATA_P_READS" BIGINT , "SKIPPED_PREFETCH_TEMP_INDEX_P_READS" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_ASYNC_COL_READS" BIGINT , "POOL_COL_WRITES" BIGINT , "POOL_ASYNC_COL_WRITES" BIGINT , "POOL_COL_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_COL_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_COL_L_READS" BIGINT , "POOL_TEMP_COL_P_READS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_TABLESPACE_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_TABLESPACE_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(128), "TBSP_PAGE_SIZE" BIGINT , "TBSP_ID" BIGINT , "TBSP_EXTENT_SIZE" BIGINT , "TBSP_PREFETCH_SIZE" BIGINT , "FS_CACHING" SMALLINT , "POOL_READ_TIME" BIGINT , "POOL_ASYNC_READ_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_ASYNC_WRITE_TIME" BIGINT , "POOL_DATA_WRITES" BIGINT , "POOL_ASYNC_DATA_WRITES" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_ASYNC_INDEX_WRITES" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_TEMP_DATA_L_READS" BIGINT , "POOL_ASYNC_DATA_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_ASYNC_INDEX_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_TEMP_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "POOL_XDA_L_READS" BIGINT , "POOL_TEMP_XDA_L_READS" BIGINT , "POOL_ASYNC_XDA_READS" BIGINT , "POOL_XDA_P_READS" BIGINT , "POOL_TEMP_XDA_P_READS" BIGINT , "POOL_XDA_WRITES" BIGINT , "POOL_ASYNC_XDA_WRITES" BIGINT , "UNREAD_PREFETCH_PAGES" BIGINT , "VECTORED_IOS" BIGINT , "PAGES_FROM_VECTORED_IOS" BIGINT , "BLOCK_IOS" BIGINT , "PAGES_FROM_BLOCK_IOS" BIGINT , "POOL_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_INDEX_LBP_PAGES_FOUND" BIGINT , "DIRECT_READ_REQS" BIGINT , "DIRECT_WRITE_REQS" BIGINT , "DIRECT_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "TBSP_USED_PAGES" BIGINT , "TBSP_PAGE_TOP" BIGINT , "POOL_DATA_GBP_L_READS" BIGINT , "POOL_DATA_GBP_P_READS" BIGINT , "POOL_INDEX_GBP_L_READS" BIGINT , "POOL_INDEX_GBP_P_READS" BIGINT , "POOL_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_L_READS" BIGINT , "POOL_ASYNC_DATA_GBP_P_READS" BIGINT , "POOL_ASYNC_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT , "POOL_ASYNC_INDEX_GBP_L_READS" BIGINT , "POOL_ASYNC_INDEX_GBP_P_READS" BIGINT , "POOL_ASYNC_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "PREFETCH_WAITS" BIGINT , "SKIPPED_PREFETCH_DATA_P_READS" BIGINT , "SKIPPED_PREFETCH_INDEX_P_READS" BIGINT , "SKIPPED_PREFETCH_TEMP_DATA_P_READS" BIGINT , "SKIPPED_PREFETCH_TEMP_INDEX_P_READS" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_ASYNC_COL_READS" BIGINT , "POOL_COL_WRITES" BIGINT , "POOL_ASYNC_COL_WRITES" BIGINT , "POOL_COL_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_COL_LBP_PAGES_FOUND" BIGINT , "POOL_TEMP_COL_L_READS" BIGINT , "POOL_TEMP_COL_P_READS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_TRANSACTION_LOG_START"
------------------------------------------------
 CREATE TABLE "MON_GET_TRANSACTION_LOG_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "LOG_WRITES" BIGINT , "LOG_WRITE_TIME" BIGINT , "NUM_LOG_WRITE_IO" BIGINT , "NUM_LOG_PART_PAGE_IO" BIGINT , "NUM_LOG_BUFFER_FULL" BIGINT , "LOG_READS" BIGINT , "LOG_READ_TIME" BIGINT , "NUM_LOG_READ_IO" BIGINT , "LOG_HADR_WAIT_TIME" BIGINT , "LOG_HADR_WAITS_TOTAL" BIGINT , "NUM_LOG_DATA_FOUND_IN_BUFFER" BIGINT , "CUR_COMMIT_LOG_BUFF_LOG_READS" BIGINT , "CUR_COMMIT_DISK_LOG_READS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_TRANSACTION_LOG_END"
------------------------------------------------
 CREATE TABLE "MON_GET_TRANSACTION_LOG_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "LOG_WRITES" BIGINT , "LOG_WRITE_TIME" BIGINT , "NUM_LOG_WRITE_IO" BIGINT , "NUM_LOG_PART_PAGE_IO" BIGINT , "NUM_LOG_BUFFER_FULL" BIGINT , "LOG_READS" BIGINT , "LOG_READ_TIME" BIGINT , "NUM_LOG_READ_IO" BIGINT , "LOG_HADR_WAIT_TIME" BIGINT , "LOG_HADR_WAITS_TOTAL" BIGINT , "NUM_LOG_DATA_FOUND_IN_BUFFER" BIGINT , "CUR_COMMIT_LOG_BUFF_LOG_READS" BIGINT , "CUR_COMMIT_DISK_LOG_READS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_TRANSACTION_LOG_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_TRANSACTION_LOG_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "LOG_WRITES" BIGINT , "LOG_WRITE_TIME" BIGINT , "NUM_LOG_WRITE_IO" BIGINT , "NUM_LOG_PART_PAGE_IO" BIGINT , "NUM_LOG_BUFFER_FULL" BIGINT , "LOG_READS" BIGINT , "LOG_READ_TIME" BIGINT , "NUM_LOG_READ_IO" BIGINT , "LOG_HADR_WAIT_TIME" BIGINT , "LOG_HADR_WAITS_TOTAL" BIGINT , "NUM_LOG_DATA_FOUND_IN_BUFFER" BIGINT , "CUR_COMMIT_LOG_BUFF_LOG_READS" BIGINT , "CUR_COMMIT_DISK_LOG_READS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_UTILITY_START"
------------------------------------------------
 CREATE TABLE "MON_GET_UTILITY_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "COORD_MEMBER" SMALLINT , "APPLICATION_HANDLE" BIGINT , "UTILITY_START_TIME" TIMESTAMP , "UTILITY_TYPE" VARCHAR(16), "UTILITY_OPERATION_TYPE" CHAR(1), "UTILITY_DETAIL" CLOB(2097152));
------------------------------------------------
-- DDL Statements for Table "MON_GET_UTILITY_END"
------------------------------------------------
 CREATE TABLE "MON_GET_UTILITY_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "COORD_MEMBER" SMALLINT , "APPLICATION_HANDLE" BIGINT , "UTILITY_START_TIME" TIMESTAMP , "UTILITY_TYPE" VARCHAR(16), "UTILITY_OPERATION_TYPE" CHAR(1), "UTILITY_DETAIL" CLOB(2097152));
------------------------------------------------
-- DDL Statements for Table "MON_GET_UTILITY_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_UTILITY_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "COORD_MEMBER" SMALLINT , "APPLICATION_HANDLE" BIGINT , "UTILITY_START_TIME" TIMESTAMP , "UTILITY_TYPE" VARCHAR(16), "UTILITY_OPERATION_TYPE" CHAR(1), "UTILITY_DETAIL" CLOB(2097152));
------------------------------------------------
-- DDL Statements for Table "MON_GET_WORKLOAD_START"
------------------------------------------------
 CREATE TABLE "MON_GET_WORKLOAD_START" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "WORKLOAD_NAME" VARCHAR(128), "SORT_SHRHEAP_ALLOCATED" BIGINT , "ACT_COMPLETED_TOTAL" BIGINT , "TOTAL_ACT_TIME" BIGINT , "TOTAL_RQST_TIME" BIGINT , "TOTAL_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "TCPIP_RECV_WAIT_TIME" BIGINT , "TCPIP_SEND_WAIT_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "TOTAL_CPU_TIME" BIGINT , "TOTAL_COMPILE_TIME" BIGINT , "TOTAL_COMPILE_PROC_TIME" BIGINT , "TOTAL_ROUTINE_TIME" BIGINT , "TOTAL_SECTION_SORT_TIME" BIGINT , "TOTAL_SECTION_SORT_PROC_TIME" BIGINT , "TOTAL_SECTION_TIME" BIGINT , "TOTAL_SECTION_PROC_TIME" BIGINT , "TOTAL_COMMIT_TIME" BIGINT , "TOTAL_ROLLBACK_TIME" BIGINT , "TOTAL_RUNSTATS_TIME" BIGINT , "TOTAL_REORG_TIME" BIGINT , "TOTAL_LOAD_TIME" BIGINT , "TOTAL_APP_COMMITS" BIGINT , "TOTAL_APP_ROLLBACKS" BIGINT , "DEADLOCKS" BIGINT , "LOCK_TIMEOUTS" BIGINT , "LOCK_ESCALS" BIGINT , "CLIENT_IDLE_WAIT_TIME" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "PKG_CACHE_INSERTS" BIGINT , "TOTAL_SORTS" BIGINT , "SORT_OVERFLOWS" BIGINT , "POST_THRESHOLD_SORTS" BIGINT , "POST_SHRTHRESHOLD_SORTS" BIGINT , "TOTAL_REORGS" BIGINT , "TOTAL_LOADS" BIGINT , "TOTAL_RUNSTATS" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "POOL_XDA_P_READS" BIGINT , "POOL_TEMP_XDA_P_READS" BIGINT , "IDA_SEND_WAIT_TIME" BIGINT , "IDA_RECV_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME_GLOBAL" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "LOG_BUFFER_WAIT_TIME" BIGINT , "LOCK_TIMEOUTS_GLOBAL" BIGINT , "LOCK_ESCALS_MAXLOCKS" BIGINT , "LOCK_ESCALS_LOCKLIST" BIGINT , "LOCK_ESCALS_GLOBAL" BIGINT , "TOTAL_ROUTINE_USER_CODE_TIME" BIGINT , "DIAGLOG_WRITE_WAIT_TIME" BIGINT , "TOTAL_CONNECT_REQUEST_TIME" BIGINT , "TOTAL_CONNECT_REQUEST_PROC_TIME" BIGINT , "AUDIT_FILE_WRITE_WAIT_TIME" BIGINT , "AUDIT_SUBSYSTEM_WAIT_TIME" BIGINT , "FCM_MESSAGE_RECV_WAIT_TIME" BIGINT , "FCM_MESSAGE_SEND_WAIT_TIME" BIGINT , "FCM_TQ_RECV_WAIT_TIME" BIGINT , "FCM_TQ_SEND_WAIT_TIME" BIGINT , "EVMON_WAIT_TIME" BIGINT , "SELECT_SQL_STMTS" BIGINT , "UID_SQL_STMTS" BIGINT , "ROWS_INSERTED" BIGINT , "ROWS_UPDATED" BIGINT , "TOTAL_COL_TIME" BIGINT , "TOTAL_COL_PROC_TIME" BIGINT , "TOTAL_BACKUP_TIME" BIGINT , "TOTAL_INDEX_BUILD_TIME" BIGINT , "TOTAL_HASH_JOINS" BIGINT , "HASH_JOIN_OVERFLOWS" BIGINT , "POST_THRESHOLD_HASH_JOINS" BIGINT , "POST_SHRTHRESHOLD_HASH_JOINS" BIGINT , "TOTAL_PEDS" BIGINT , "POST_THRESHOLD_PEDS" BIGINT , "DISABLED_PEDS" BIGINT , "TOTAL_PEAS" BIGINT , "POST_THRESHOLD_PEAS" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_TEMP_COL_P_READS" BIGINT , "COMM_EXIT_WAIT_TIME" BIGINT , "TOTAL_COL_SYNOPSIS_TIME" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_RECVS_TOTAL" BIGINT , "EXT_TABLE_RECV_VOLUME" BIGINT , "EXT_TABLE_READ_VOLUME" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "EXT_TABLE_SENDS_TOTAL" BIGINT , "EXT_TABLE_SEND_VOLUME" BIGINT , "EXT_TABLE_WRITE_VOLUME" BIGINT , "LOB_PREFETCH_WAIT_TIME" BIGINT , "FED_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_WORKLOAD_END"
------------------------------------------------
 CREATE TABLE "MON_GET_WORKLOAD_END" ("TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "WORKLOAD_NAME" VARCHAR(128), "SORT_SHRHEAP_ALLOCATED" BIGINT , "ACT_COMPLETED_TOTAL" BIGINT , "TOTAL_ACT_TIME" BIGINT , "TOTAL_RQST_TIME" BIGINT , "TOTAL_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "TCPIP_RECV_WAIT_TIME" BIGINT , "TCPIP_SEND_WAIT_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "TOTAL_CPU_TIME" BIGINT , "TOTAL_COMPILE_TIME" BIGINT , "TOTAL_COMPILE_PROC_TIME" BIGINT , "TOTAL_ROUTINE_TIME" BIGINT , "TOTAL_SECTION_SORT_TIME" BIGINT , "TOTAL_SECTION_SORT_PROC_TIME" BIGINT , "TOTAL_SECTION_TIME" BIGINT , "TOTAL_SECTION_PROC_TIME" BIGINT , "TOTAL_COMMIT_TIME" BIGINT , "TOTAL_ROLLBACK_TIME" BIGINT , "TOTAL_RUNSTATS_TIME" BIGINT , "TOTAL_REORG_TIME" BIGINT , "TOTAL_LOAD_TIME" BIGINT , "TOTAL_APP_COMMITS" BIGINT , "TOTAL_APP_ROLLBACKS" BIGINT , "DEADLOCKS" BIGINT , "LOCK_TIMEOUTS" BIGINT , "LOCK_ESCALS" BIGINT , "CLIENT_IDLE_WAIT_TIME" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "PKG_CACHE_INSERTS" BIGINT , "TOTAL_SORTS" BIGINT , "SORT_OVERFLOWS" BIGINT , "POST_THRESHOLD_SORTS" BIGINT , "POST_SHRTHRESHOLD_SORTS" BIGINT , "TOTAL_REORGS" BIGINT , "TOTAL_LOADS" BIGINT , "TOTAL_RUNSTATS" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "POOL_XDA_P_READS" BIGINT , "POOL_TEMP_XDA_P_READS" BIGINT , "IDA_SEND_WAIT_TIME" BIGINT , "IDA_RECV_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME_GLOBAL" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "LOG_BUFFER_WAIT_TIME" BIGINT , "LOCK_TIMEOUTS_GLOBAL" BIGINT , "LOCK_ESCALS_MAXLOCKS" BIGINT , "LOCK_ESCALS_LOCKLIST" BIGINT , "LOCK_ESCALS_GLOBAL" BIGINT , "TOTAL_ROUTINE_USER_CODE_TIME" BIGINT , "DIAGLOG_WRITE_WAIT_TIME" BIGINT , "TOTAL_CONNECT_REQUEST_TIME" BIGINT , "TOTAL_CONNECT_REQUEST_PROC_TIME" BIGINT , "AUDIT_FILE_WRITE_WAIT_TIME" BIGINT , "AUDIT_SUBSYSTEM_WAIT_TIME" BIGINT , "FCM_MESSAGE_RECV_WAIT_TIME" BIGINT , "FCM_MESSAGE_SEND_WAIT_TIME" BIGINT , "FCM_TQ_RECV_WAIT_TIME" BIGINT , "FCM_TQ_SEND_WAIT_TIME" BIGINT , "EVMON_WAIT_TIME" BIGINT , "SELECT_SQL_STMTS" BIGINT , "UID_SQL_STMTS" BIGINT , "ROWS_INSERTED" BIGINT , "ROWS_UPDATED" BIGINT , "TOTAL_COL_TIME" BIGINT , "TOTAL_COL_PROC_TIME" BIGINT , "TOTAL_BACKUP_TIME" BIGINT , "TOTAL_INDEX_BUILD_TIME" BIGINT , "TOTAL_HASH_JOINS" BIGINT , "HASH_JOIN_OVERFLOWS" BIGINT , "POST_THRESHOLD_HASH_JOINS" BIGINT , "POST_SHRTHRESHOLD_HASH_JOINS" BIGINT , "TOTAL_PEDS" BIGINT , "POST_THRESHOLD_PEDS" BIGINT , "DISABLED_PEDS" BIGINT , "TOTAL_PEAS" BIGINT , "POST_THRESHOLD_PEAS" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_TEMP_COL_P_READS" BIGINT , "COMM_EXIT_WAIT_TIME" BIGINT , "TOTAL_COL_SYNOPSIS_TIME" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_RECVS_TOTAL" BIGINT , "EXT_TABLE_RECV_VOLUME" BIGINT , "EXT_TABLE_READ_VOLUME" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "EXT_TABLE_SENDS_TOTAL" BIGINT , "EXT_TABLE_SEND_VOLUME" BIGINT , "EXT_TABLE_WRITE_VOLUME" BIGINT , "LOB_PREFETCH_WAIT_TIME" BIGINT , "FED_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_GET_WORKLOAD_DIFF"
------------------------------------------------
 CREATE TABLE "MON_GET_WORKLOAD_DIFF" ("TS_DELTA" INTEGER , "TS" TIMESTAMP NOT NULL, "MEMBER" SMALLINT , "WORKLOAD_NAME" VARCHAR(128), "SORT_SHRHEAP_ALLOCATED" BIGINT , "ACT_COMPLETED_TOTAL" BIGINT , "TOTAL_ACT_TIME" BIGINT , "TOTAL_RQST_TIME" BIGINT , "TOTAL_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "POOL_WRITE_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "TCPIP_RECV_WAIT_TIME" BIGINT , "TCPIP_SEND_WAIT_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "TOTAL_CPU_TIME" BIGINT , "TOTAL_COMPILE_TIME" BIGINT , "TOTAL_COMPILE_PROC_TIME" BIGINT , "TOTAL_ROUTINE_TIME" BIGINT , "TOTAL_SECTION_SORT_TIME" BIGINT , "TOTAL_SECTION_SORT_PROC_TIME" BIGINT , "TOTAL_SECTION_TIME" BIGINT , "TOTAL_SECTION_PROC_TIME" BIGINT , "TOTAL_COMMIT_TIME" BIGINT , "TOTAL_ROLLBACK_TIME" BIGINT , "TOTAL_RUNSTATS_TIME" BIGINT , "TOTAL_REORG_TIME" BIGINT , "TOTAL_LOAD_TIME" BIGINT , "TOTAL_APP_COMMITS" BIGINT , "TOTAL_APP_ROLLBACKS" BIGINT , "DEADLOCKS" BIGINT , "LOCK_TIMEOUTS" BIGINT , "LOCK_ESCALS" BIGINT , "CLIENT_IDLE_WAIT_TIME" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "PKG_CACHE_INSERTS" BIGINT , "TOTAL_SORTS" BIGINT , "SORT_OVERFLOWS" BIGINT , "POST_THRESHOLD_SORTS" BIGINT , "POST_SHRTHRESHOLD_SORTS" BIGINT , "TOTAL_REORGS" BIGINT , "TOTAL_LOADS" BIGINT , "TOTAL_RUNSTATS" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_TEMP_DATA_P_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_TEMP_INDEX_P_READS" BIGINT , "POOL_XDA_P_READS" BIGINT , "POOL_TEMP_XDA_P_READS" BIGINT , "IDA_SEND_WAIT_TIME" BIGINT , "IDA_RECV_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME_GLOBAL" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "PREFETCH_WAIT_TIME" BIGINT , "LOG_BUFFER_WAIT_TIME" BIGINT , "LOCK_TIMEOUTS_GLOBAL" BIGINT , "LOCK_ESCALS_MAXLOCKS" BIGINT , "LOCK_ESCALS_LOCKLIST" BIGINT , "LOCK_ESCALS_GLOBAL" BIGINT , "TOTAL_ROUTINE_USER_CODE_TIME" BIGINT , "DIAGLOG_WRITE_WAIT_TIME" BIGINT , "TOTAL_CONNECT_REQUEST_TIME" BIGINT , "TOTAL_CONNECT_REQUEST_PROC_TIME" BIGINT , "AUDIT_FILE_WRITE_WAIT_TIME" BIGINT , "AUDIT_SUBSYSTEM_WAIT_TIME" BIGINT , "FCM_MESSAGE_RECV_WAIT_TIME" BIGINT , "FCM_MESSAGE_SEND_WAIT_TIME" BIGINT , "FCM_TQ_RECV_WAIT_TIME" BIGINT , "FCM_TQ_SEND_WAIT_TIME" BIGINT , "EVMON_WAIT_TIME" BIGINT , "SELECT_SQL_STMTS" BIGINT , "UID_SQL_STMTS" BIGINT , "ROWS_INSERTED" BIGINT , "ROWS_UPDATED" BIGINT , "TOTAL_COL_TIME" BIGINT , "TOTAL_COL_PROC_TIME" BIGINT , "TOTAL_BACKUP_TIME" BIGINT , "TOTAL_INDEX_BUILD_TIME" BIGINT , "TOTAL_HASH_JOINS" BIGINT , "HASH_JOIN_OVERFLOWS" BIGINT , "POST_THRESHOLD_HASH_JOINS" BIGINT , "POST_SHRTHRESHOLD_HASH_JOINS" BIGINT , "TOTAL_PEDS" BIGINT , "POST_THRESHOLD_PEDS" BIGINT , "DISABLED_PEDS" BIGINT , "TOTAL_PEAS" BIGINT , "POST_THRESHOLD_PEAS" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_TEMP_COL_P_READS" BIGINT , "COMM_EXIT_WAIT_TIME" BIGINT , "TOTAL_COL_SYNOPSIS_TIME" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_RECVS_TOTAL" BIGINT , "EXT_TABLE_RECV_VOLUME" BIGINT , "EXT_TABLE_READ_VOLUME" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "EXT_TABLE_SENDS_TOTAL" BIGINT , "EXT_TABLE_SEND_VOLUME" BIGINT , "EXT_TABLE_WRITE_VOLUME" BIGINT , "LOB_PREFETCH_WAIT_TIME" BIGINT , "FED_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "MON_CURRENT_SQL_PLUS_START"
------------------------------------------------
 CREATE TABLE "MON_CURRENT_SQL_PLUS_START" ("TS" TIMESTAMP NOT NULL, "COUNT" INTEGER NOT NULL, "COORD_MEMBER" SMALLINT , "APPLICATION_HANDLE" BIGINT , "UOW_ID" INTEGER , "ACTIVITY_ID" INTEGER , "ELAPSED_TIME_SEC" INTEGER , "TOTAL_CPU_TIME" BIGINT , "ROWS_READ" BIGINT , "DIRECT_READS" BIGINT , "DIRECT_WRITES" BIGINT , "EXECUTABLE_ID" VARCHAR(32), "PACKAGE_NAME" VARCHAR(128), "SECTION_NUMBER" BIGINT , "ACTIVE_SORTS" BIGINT , "ACTIVE_SORTS_TOP" BIGINT , "ACTIVE_SORT_CONSUMERS" BIGINT , "ACTIVE_SORT_CONSUMERS_TOP" BIGINT , "SORT_SHRHEAP_ALLOCATED" BIGINT , "SORT_SHRHEAP_TOP" BIGINT , "POST_THRESHOLD_SORTS" BIGINT , "POST_SHRTHRESHOLD_SORTS" BIGINT , "POST_THRESHOLD_HASH_JOINS" BIGINT , "POST_SHRTHRESHOLD_HASH_JOINS" BIGINT , "POST_THRESHOLD_HASH_GRPBYS" BIGINT , "POST_THRESHOLD_OLAP_FUNCS" BIGINT , "TOTAL_ACT_TIME" BIGINT , "TOTAL_ACT_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "SPACEMAPPAGE_RECLAIM_WAIT_TIME" BIGINT , "STMT_TEXT" CLOB(2097152));
------------------------------------------------
-- DDL Statements for Table "MON_CURRENT_SQL_PLUS_END"
------------------------------------------------
 CREATE TABLE "MON_CURRENT_SQL_PLUS_END" ("TS" TIMESTAMP NOT NULL, "COUNT" INTEGER NOT NULL, "COORD_MEMBER" SMALLINT , "APPLICATION_HANDLE" BIGINT , "UOW_ID" INTEGER , "ACTIVITY_ID" INTEGER , "ELAPSED_TIME_SEC" INTEGER , "TOTAL_CPU_TIME" BIGINT , "ROWS_READ" BIGINT , "DIRECT_READS" BIGINT , "DIRECT_WRITES" BIGINT , "EXECUTABLE_ID" VARCHAR(32), "PACKAGE_NAME" VARCHAR(128), "SECTION_NUMBER" BIGINT , "ACTIVE_SORTS" BIGINT , "ACTIVE_SORTS_TOP" BIGINT , "ACTIVE_SORT_CONSUMERS" BIGINT , "ACTIVE_SORT_CONSUMERS_TOP" BIGINT , "SORT_SHRHEAP_ALLOCATED" BIGINT , "SORT_SHRHEAP_TOP" BIGINT , "POST_THRESHOLD_SORTS" BIGINT , "POST_SHRTHRESHOLD_SORTS" BIGINT , "POST_THRESHOLD_HASH_JOINS" BIGINT , "POST_SHRTHRESHOLD_HASH_JOINS" BIGINT , "POST_THRESHOLD_HASH_GRPBYS" BIGINT , "POST_THRESHOLD_OLAP_FUNCS" BIGINT , "TOTAL_ACT_TIME" BIGINT , "TOTAL_ACT_WAIT_TIME" BIGINT , "LOCK_WAIT_TIME" BIGINT , "POOL_READ_TIME" BIGINT , "DIRECT_READ_TIME" BIGINT , "DIRECT_WRITE_TIME" BIGINT , "FCM_RECV_WAIT_TIME" BIGINT , "FCM_SEND_WAIT_TIME" BIGINT , "TOTAL_EXTENDED_LATCH_WAIT_TIME" BIGINT , "LOG_DISK_WAIT_TIME" BIGINT , "CF_WAIT_TIME" BIGINT , "RECLAIM_WAIT_TIME" BIGINT , "SPACEMAPPAGE_RECLAIM_WAIT_TIME" BIGINT , "STMT_TEXT" CLOB(2097152));
------------------------------------------------
-- DDL Statements for Table "MON_GET_LOCKS_START"
------------------------------------------------
 CREATE TABLE "MON_GET_LOCKS_START" ("TBSPACE" VARCHAR(20), "TABNAME" VARCHAR(30), "LOCK_OBJ_TYPE" VARCHAR(12), "LOCK_NAME" VARCHAR(32), "LOCK_MODE" VARCHAR(3), "LOCK_STATUS" CHAR(1), "MEMBER" SMALLINT , "APPHDL" INTEGER);
------------------------------------------------
-- DDL Statements for Table "MON_GET_LOCKS_END"
------------------------------------------------
 CREATE TABLE "MON_GET_LOCKS_END" ("TBSPACE" VARCHAR(20), "TABNAME" VARCHAR(30), "LOCK_OBJ_TYPE" VARCHAR(12), "LOCK_NAME" VARCHAR(32), "LOCK_MODE" VARCHAR(3), "LOCK_STATUS" CHAR(1), "MEMBER" SMALLINT , "APPHDL" INTEGER);
------------------------------------------------
-- DDL Statements for Table "START_LOCKW"
------------------------------------------------
 CREATE TABLE "START_LOCKW" ("TBSPACE" VARCHAR(20), "TABNAME" VARCHAR(30), "LOCK_OBJ_TYPE" VARCHAR(12), "LOCK_NAME" VARCHAR(32), "LOCK_MODE" VARCHAR(3), "LOCK_STATUS" CHAR(1), "MEMBER" SMALLINT , "APPHDL" INTEGER);
------------------------------------------------
-- DDL Statements for Table "START_EXUTL"
------------------------------------------------
 CREATE TABLE "START_EXUTL" ("MEMBER" SMALLINT , "COORD_MEMBER" SMALLINT , "APPLICATION_HANDLE" BIGINT , "UTILITY_START_TIME" TIMESTAMP , "UTILITY_TYPE" VARCHAR(16), "UTILITY_OPERATION_TYPE" CHAR(1), "UTILITY_DETAIL" VARCHAR(100));
------------------------------------------------
-- DDL Statements for Table "END_LOCKW"
------------------------------------------------
 CREATE TABLE "END_LOCKW" ("TBSPACE" VARCHAR(20), "TABNAME" VARCHAR(30), "LOCK_OBJ_TYPE" VARCHAR(12), "LOCK_NAME" VARCHAR(32), "LOCK_MODE" VARCHAR(3), "LOCK_STATUS" CHAR(1), "MEMBER" SMALLINT , "APPHDL" INTEGER);
------------------------------------------------
-- DDL Statements for Table "END_EXUTL"
------------------------------------------------
 CREATE TABLE "END_EXUTL" ("MEMBER" SMALLINT , "COORD_MEMBER" SMALLINT , "APPLICATION_HANDLE" BIGINT , "UTILITY_START_TIME" TIMESTAMP , "UTILITY_TYPE" VARCHAR(16), "UTILITY_OPERATION_TYPE" CHAR(1), "UTILITY_DETAIL" VARCHAR(100));
------------------------------------------------
-- DDL Statements for Table "DB_THRUP"
------------------------------------------------
 CREATE TABLE "DB_THRUP" ("TS_DELTA" INTEGER , "MEMBER" SMALLINT , "ACT_PER_S" DECIMAL(10,1), "CMT_PER_S" DECIMAL(10,1), "RB_PER_S" DECIMAL(10,1), "DDLCK_PER_S" DECIMAL(10,1), "SEL_P_S" DECIMAL(10,1), "UID_P_S" DECIMAL(10,1), "ROWS_INS_P_S" DECIMAL(10,1), "ROWS_UPD_P_S" DECIMAL(10,1), "ROWS_RET_P_S" DECIMAL(10,1), "ROWS_MOD_P_S" DECIMAL(10,1), "PKG_CACHE_INS_P_S" DECIMAL(10,1), "P_RD_PER_S" DECIMAL(10,1));
------------------------------------------------
-- DDL Statements for Table "DB_CLACT"
------------------------------------------------
 CREATE TABLE "DB_CLACT" ("MEMBER" SMALLINT , "TOTAL_CLIENTS" INTEGER NOT NULL, "TOTAL_CIWT" BIGINT , "TOTAL_RQST" BIGINT , "TOT_CIWT_RQ_RATIO" DECIMAL(10,2), "ACTIVE_CLIENTS" INTEGER NOT NULL, "ACTIVE_RQ_PER_S" DECIMAL(10,2), "ACTIVE_CIWT" BIGINT , "ACTIVE_RQST" BIGINT , "ACTIVE_CIWT_RQ_RATIO" DECIMAL(10,2));
------------------------------------------------
-- DDL Statements for Table "DB_TIMEB"
------------------------------------------------
 CREATE TABLE "DB_TIMEB" ("MEMBER" SMALLINT , "TOTAL_RQST_TM" INTEGER , "PCT_COMPILE" DECIMAL(5,2), "PCT_SECTION" DECIMAL(5,2), "PCT_SORT" DECIMAL(5,2), "PCT_COL" DECIMAL(5,2), "PCT_COL_SYNOP" DECIMAL(5,2), "PCT_COMMIT" DECIMAL(5,2), "PCT_RBACK" DECIMAL(5,2), "PCT_CONN" DECIMAL(5,2), "PCT_RTN_USR_CODE" DECIMAL(5,2), "PCT_BACKUP" DECIMAL(5,2), "PCT_IDX_BLD" DECIMAL(5,2), "PCT_RUNSTATS" DECIMAL(5,2), "PCT_REORG" DECIMAL(5,2), "PCT_LOAD" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "DB_WAITT"
------------------------------------------------
 CREATE TABLE "DB_WAITT" ("MEMBER" SMALLINT , "TOTAL_RQST_TM" INTEGER , "TOTAL_WAIT_TM" INTEGER ,"TOTAL_CPU_TM" INTEGER , "PCT_RQST_WAIT" DECIMAL(5,2), "PCT_LOCK" DECIMAL(5,2), "PCT_GLB_LOCK" DECIMAL(5,2), "PCT_LTCH" DECIMAL(5,2), "PCT_LG_DSK" DECIMAL(5,2), "PCT_LG_BUF" DECIMAL(5,2), "PCT_RCLM" DECIMAL(5,2), "PCT_CF" DECIMAL(5,2), "PCT_PFTCH" DECIMAL(5,2), "PCT_DIAG" DECIMAL(5,2), "PCT_AUD_W" DECIMAL(5,2), "PCT_AUD_SS" DECIMAL(5,2), "PCT_EVMON" DECIMAL(5,2), "PCT_COMMEXIT" DECIMAL(5,2), "PCT_LOB_PFTCH" DECIMAL(5,2), "PCT_EXTBL" DECIMAL(5,2), "PCT_FED" DECIMAL(5,2), "PCT_POOL_R" DECIMAL(5,2),"PCT_POOL_W" DECIMAL(5,2), "PCT_DIR_R" DECIMAL(5,2), "PCT_DIR_W" DECIMAL(5,2), "PCT_FCM" DECIMAL(5,2), "PCT_TCPIP" DECIMAL(5,2), "PCT_IDA" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "DB_PROCT"
------------------------------------------------
 CREATE TABLE "DB_PROCT" ("MEMBER" SMALLINT , "TOTAL_RQST_TM" INTEGER , "TOTAL_PROC_TIME" INTEGER , "PCT_COMP_PROC" DECIMAL(5,2), "PCT_SECT_PROC" DECIMAL(5,2), "PCT_SECT_SORT_PROC" DECIMAL(5,2), "PCT_COMMIT" DECIMAL(5,2), "PCT_RBACK" DECIMAL(5,2), "PCT_COL_PROC" DECIMAL(5,2), "PCT_CONN_PROC" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "DB_SORT"
------------------------------------------------
 CREATE TABLE "DB_SORT" ("MEMBER" SMALLINT , "TOTAL_SORTS" INTEGER , "SORT_OVERFLOWS" INTEGER , "TOT_SECT_SORT_TM" BIGINT , "TOT_SECT_SORT_PROC_TM" BIGINT , "SORT_SHRHEAP_ALLOCATED" BIGINT , "TOTAL_HSJN" INTEGER , "HSJN_OVFL" INTEGER , "PST_THR_HSJN" INTEGER , "PST_SHRTHR_HSJN" INTEGER);
------------------------------------------------
-- DDL Statements for Table "SQL_TOPEXECT"
------------------------------------------------
 CREATE TABLE "SQL_TOPEXECT" ("MEMBER" SMALLINT , "NUM_EXEC" INTEGER , "COORD_STMT_EXEC_TIME" BIGINT , "AVG_COORD_EXEC_TIME" DECIMAL(10,2), "PCT_COORD_STMT_EXEC_TIME" DECIMAL(5,2), "TOTAL_ACT_TIME" BIGINT , "TOTAL_CPU_TIME" BIGINT , "AVG_CPU_TIME" BIGINT , "PCT_WAIT_TIME" DECIMAL(13,2), "AVG_SECT_TIME" DECIMAL(20,2), "AVG_COL_TIME" DECIMAL(20,2), "ISO" CHAR(2), "STMT_TEXT" VARCHAR(200));
------------------------------------------------
-- DDL Statements for Table "SQL_TOPEXECP"
------------------------------------------------
 CREATE TABLE "SQL_TOPEXECP" ("MEMBER" SMALLINT , "NUM_STMTS" INTEGER NOT NULL, "TOTAL_EXEC" INTEGER , "COORD_STMT_EXEC_TIME" BIGINT , "AVG_COORD_EXEC_TIME" DECIMAL(10,2), "PCT_COORD_STMT_EXEC_TIME" DECIMAL(5,2), "TOTAL_ACT_TIME" BIGINT , "TOTAL_CPU_TIME" BIGINT , "AVG_CPU_TIME" BIGINT , "PCT_WAIT_TIME" DECIMAL(13,2), "AVG_SECT_TIME" DECIMAL(20,2), "AVG_COL_TIME" DECIMAL(20,2), "STMT_TEXT" VARCHAR(200));
------------------------------------------------
-- DDL Statements for Table "PKG_EXECT"
------------------------------------------------
 CREATE TABLE "PKG_EXECT" ("MEMBER" SMALLINT , "PACKAGE_NAME" VARCHAR(20), "NUM_STMTS_EXEC" BIGINT , "COORD_STMT_EXEC_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "SQL_TOPWAITT"
------------------------------------------------
 CREATE TABLE "SQL_TOPWAITT" ("MEMBER" SMALLINT , "PCT_WAIT" DECIMAL(5,2), "PCT_LG_DSK" DECIMAL(5,2), "PCT_LG_BUF" DECIMAL(5,2), "PCT_LOCK" DECIMAL(5,2), "PCT_GLB_LOCK" DECIMAL(5,2), "PCT_LTCH" DECIMAL(5,2), "PCT_RCLM" DECIMAL(5,2), "PCT_CF" DECIMAL(5,2), "PCT_PFTCH" DECIMAL(5,2), "PCT_DIAG" DECIMAL(5,2), "PCT_POOL_R" DECIMAL(5,2), "PCT_DIR_R" DECIMAL(5,2), "PCT_DIR_W" DECIMAL(5,2), "PCT_FCM" DECIMAL(5,2), "PCT_AUD_W" DECIMAL(5,2), "PCT_AUD_SS" DECIMAL(5,2), "PCT_EVMON" DECIMAL(5,2), "PCT_COMMEXIT" DECIMAL(5,2), "PCT_LOB_PFTCH" DECIMAL(5,2), "PCT_EXTBL" DECIMAL(5,2), "PCT_FED" DECIMAL(5,2), "PCT_IDA" DECIMAL(5,2), "STMT_TEXT" VARCHAR(200));
------------------------------------------------
-- DDL Statements for Table "SQL_TOPWAITW"
------------------------------------------------
 CREATE TABLE "SQL_TOPWAITW" ("MEMBER" SMALLINT , "PCT_WAIT" DECIMAL(5,2), "PCT_LG_DSK" DECIMAL(5,2), "PCT_LG_BUF" DECIMAL(5,2), "PCT_LOCK" DECIMAL(5,2), "PCT_GLB_LOCK" DECIMAL(5,2), "PCT_LTCH" DECIMAL(5,2), "PCT_RCLM" DECIMAL(5,2), "PCT_CF" DECIMAL(5,2), "PCT_PFTCH" DECIMAL(5,2), "PCT_DIAG" DECIMAL(5,2), "PCT_POOL_R" DECIMAL(5,2), "PCT_DIR_R" DECIMAL(5,2), "PCT_DIR_W" DECIMAL(5,2), "PCT_FCM" DECIMAL(5,2), "PCT_AUD_W" DECIMAL(5,2), "PCT_AUD_SS" DECIMAL(5,2), "PCT_EVMON" DECIMAL(5,2), "PCT_COMMEXIT" DECIMAL(5,2), "PCT_LOB_PFTCH" DECIMAL(5,2), "PCT_EXTBL" DECIMAL(5,2), "PCT_FED" DECIMAL(5,2), "PCT_IDA" DECIMAL(5,2), "STMT_TEXT" VARCHAR(200));
------------------------------------------------
-- DDL Statements for Table "SQL_TOPIOSTA"
------------------------------------------------
 CREATE TABLE "SQL_TOPIOSTA" ("MEMBER" SMALLINT , "NUM_EXEC" INTEGER , "AVG_D_LRD" DECIMAL(16,1), "AVG_D_PRD" DECIMAL(10,1), "AVG_I_LRD" DECIMAL(16,1), "AVG_I_PRD" DECIMAL(10,1), "AVG_TD_PRD" DECIMAL(10,1), "AVG_TI_PRD" DECIMAL(10,1), "AVG_COL_LRD" DECIMAL(16,1), "AVG_COL_PRD" DECIMAL(10,1), "AVG_DIR_R_RQS" DECIMAL(8,1), "AVG_DIR_W_RQS" DECIMAL(8,1), "STMT_TEXT" VARCHAR(200));
------------------------------------------------
-- DDL Statements for Table "SQL_TOPROWS"
------------------------------------------------
 CREATE TABLE "SQL_TOPROWS" ("MEMBER" SMALLINT , "NUM_EXEC" INTEGER , "AVG_ROWS_MOD" DECIMAL(12,1), "AVG_ROWS_READ" DECIMAL(12,1), "AVG_ROWS_RET" DECIMAL(12,1), "COL_SYNOPSIS_ROWS_INSERTED" BIGINT , "STMT_TEXT" VARCHAR(200));
------------------------------------------------
-- DDL Statements for Table "SQL_TOPSORT"
------------------------------------------------
 CREATE TABLE "SQL_TOPSORT" ("MEMBER" SMALLINT , "PCT_SORT_TIME" DECIMAL(13,2), "AVG_TOT_SORTS" DECIMAL(8,1), "AVG_SORT_OVFLWS" DECIMAL(8,1), "ACTIVE_SORTS_TOP" INTEGER , "SORT_HEAP_TOP" INTEGER , "STMT_TEXT" VARCHAR(200));
------------------------------------------------
-- DDL Statements for Table "INF_EXPLN"
------------------------------------------------
 CREATE TABLE "INF_EXPLN" ("MEMBER" SMALLINT , "EXECUTABLE_ID" VARCHAR(32), "PLANID" BIGINT , "STMTID" BIGINT , "SEMANTIC_ENV_ID" BIGINT , "STMT_TEXT" VARCHAR(200));
------------------------------------------------
-- DDL Statements for Table "DB_SYSRE"
------------------------------------------------
 CREATE TABLE "DB_SYSRE" ("MEMBER" SMALLINT , "OS" VARCHAR(8), "HOST_NAME" VARCHAR(16), "OS_VER" VARCHAR(8), "OS_REL" VARCHAR(8), "CPU_TOT" SMALLINT , "CPU_ONL" SMALLINT , "CPU_CFG" SMALLINT , "CPU_SPEED" INTEGER , "CPU_HMT" SMALLINT , "MEMORY_TOTAL" INTEGER , "MEMORY_FREE" INTEGER , "CPU_LOAD_SHRT" DECIMAL(6,1), "CPU_LOAD_MED" DECIMAL(6,1), "CPU_LOAD_LNG" DECIMAL(6,1), "CPU_USAGE_TOT" DECIMAL(6,1), "SWAP_PAGES_IN" INTEGER , "SWAP_PAGES_OUT" INTEGER);
------------------------------------------------
-- DDL Statements for Table "DB_LOGWR"
------------------------------------------------
 CREATE TABLE "DB_LOGWR" ("MEMBER" SMALLINT , "NUM_LOG_WRITE_IO" BIGINT , "LOG_WRITE_IO_PER_S" DECIMAL(10,4), "LOG_WRITE_MB_PER_S" DECIMAL(10,4), "LOG_WRITE_TIME" BIGINT , "LOG_WRITE_TIME_PER_IO_MS" DECIMAL(10,4), "NUM_LOG_BUFFER_FULL" BIGINT);
------------------------------------------------
-- DDL Statements for Table "DB_LOGRE"
------------------------------------------------
 CREATE TABLE "DB_LOGRE" ("MEMBER" SMALLINT , "NUM_LOG_READ_IO" INTEGER , "LOG_READ_IO_PER_S" DECIMAL(10,4), "LOG_READS" INTEGER , "LOG_READ_TIME" INTEGER , "LOG_READ_TIME_PER_IO_MS" DECIMAL(10,4), "NUM_LOG_DATA_IN_BUFFER" INTEGER , "CUR_COM_LOG_BUFF_LOG_READS" INTEGER , "CUR_COM_DISK_LOG_READS" INTEGER);
------------------------------------------------
-- DDL Statements for Table "DB_LOGST"
------------------------------------------------
 CREATE TABLE "DB_LOGST" ("MEMBER" SMALLINT , "NUM_LOG_WRITE_IO" BIGINT , "NUM_LOG_PART_PAGE_IO" BIGINT , "LOG_PART_PAGE_RATIO" DECIMAL(10,4), "AVG_LOG_HADR_WAIT_TIME" DECIMAL(10,4));
------------------------------------------------
-- DDL Statements for Table "TSP_DSKIO"
------------------------------------------------
 CREATE TABLE "TSP_DSKIO" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(20), "NUM_READS" BIGINT , "AVG_READ_TIME" DECIMAL(10,2), "DIRECT_READ_REQS" BIGINT , "AVG_DRCT_READ_TIME" DECIMAL(10,2), "NUM_WRITES" BIGINT , "AVG_WRITE_TIME" DECIMAL(10,2), "DIRECT_WRITE_REQS" BIGINT , "AVG_DRCT_WRITE_TIME" DECIMAL(10,2));
------------------------------------------------
-- DDL Statements for Table "TSP_DSKIOSYNC"
------------------------------------------------
 CREATE TABLE "TSP_DSKIOSYNC" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(20), "NUM_READS" BIGINT , "AVG_SYNC_READ_TIME" DECIMAL(10,2), "NUM_WRITES" BIGINT , "AVG_SYNC_WRITE_TIME" DECIMAL(10,2));
------------------------------------------------
-- DDL Statements for Table "TSP_SKIOASYNC"
------------------------------------------------
 CREATE TABLE "TSP_SKIOASYNC" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(20), "NUM_READS" BIGINT , "AVG_ASYNC_READ_TIME" DECIMAL(5,2), "NUM_WRITES" BIGINT , "AVG_ASYNC_WRITE_TIME" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "DB_EXTBM"
------------------------------------------------
 CREATE TABLE "DB_EXTBM" ("MEMBER" SMALLINT , "EXT_TABLE_RECVS_TOTAL" BIGINT , "EXT_TABLE_RECV_WAIT_TIME" BIGINT , "EXT_TABLE_RECV_VOLUME" BIGINT , "EXT_TABLE_READ_VOLUME" BIGINT , "EXT_TABLE_SENDS_TOTAL" BIGINT , "EXT_TABLE_SEND_WAIT_TIME" BIGINT , "EXT_TABLE_SEND_VOLUME" BIGINT , "EXT_TABLE_WRITE_VOLUME" BIGINT , "RECV_PER_S" DECIMAL(10,1), "READ_PER_S" DECIMAL(10,1), "SEND_PER_S" DECIMAL(10,1), "WRITE_PER_S" DECIMAL(10,1));
------------------------------------------------
-- DDL Statements for Table "LTC_WAITT"
------------------------------------------------
 CREATE TABLE "LTC_WAITT" ("MEMBER" SMALLINT , "LATCH_NAME" VARCHAR(60), "TOT_EXT_LATCH_WAIT_TIME_MS" BIGINT , "TOT_EXT_LATCH_WAITS" BIGINT , "TIME_PER_LATCH_WAIT_MS" DECIMAL(10,2));
------------------------------------------------
-- DDL Statements for Table "DB_DLCKS"
------------------------------------------------
 CREATE TABLE "DB_DLCKS" ("MEMBER" SMALLINT , "DEADLOCKS" INTEGER , "LOCK_TIMEOUTS" INTEGER , "LOCK_ESCALS" INTEGER , "LOCK_TIMEOUTS_LOCAL" INTEGER , "LOCK_TIMEOUTS_GLOBAL" INTEGER , "LOCK_ESCALS_MAXLOCKS" INTEGER , "LOCK_ESCALS_LOCKLIST" INTEGER , "LOCK_ESCALS_GLOBAL" INTEGER);
------------------------------------------------
-- DDL Statements for Table "TBL_DATSH"
------------------------------------------------
 CREATE TABLE "TBL_DATSH" ("MEMBER" SMALLINT , "TABNAME" VARCHAR(40), "DATA_PART_ID" INTEGER , "DATA_SHARING_STATE_CHANGE_TIME" TIMESTAMP , "DATA_SHARING_STATE" VARCHAR(19), "DATA_SHARING_REMOTE_LOCKWAIT_COUNT" BIGINT , "DATA_SHARING_REMOTE_LOCKWAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "DB_SIZE"
------------------------------------------------
 CREATE TABLE "DB_SIZE" ("MEMBER" SMALLINT , "DB_MB_USED" BIGINT);
------------------------------------------------
-- DDL Statements for Table "TSP_SIZE"
------------------------------------------------
 CREATE TABLE "TSP_SIZE" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(32), "TBSP_ID" BIGINT , "TBSP_PAGE_SIZE" BIGINT , "TBSP_USED_PAGES" BIGINT , "TBSP_MB_USED" DECIMAL(10,2), "TBSP_MB_HWM" DECIMAL(10,2), "TBSP_EXTENT_SIZE" BIGINT , "FS_CACHING" VARCHAR(12) NOT NULL, "TBSP_PREFETCH_SIZE" BIGINT);
------------------------------------------------
-- DDL Statements for Table "TSP_USAGE"
------------------------------------------------
 CREATE TABLE "TSP_USAGE" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(30), "TBSP_USED_PAGES" BIGINT , "TBSP_MB_USED" DECIMAL(10,2));
------------------------------------------------
-- DDL Statements for Table "BPL_STATS"
------------------------------------------------
 CREATE TABLE "BPL_STATS" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(20), "DATA_L_READS" BIGINT , "DATA_P_READS" BIGINT , "SYNC_DATA_P_READS" BIGINT , "DATA_HR" DECIMAL(5,2), "DATA_LBP_HR" DECIMAL(5,2), "COL_L_READS" BIGINT , "COL_P_READS" BIGINT , "SYNC_COL_P_READS" BIGINT , "COL_HR" DECIMAL(5,2), "INDEX_L_READS" BIGINT , "INDEX_P_READS" BIGINT , "SYNC_INDEX_P_READS" BIGINT , "INDEX_HR" DECIMAL(5,2), "INDEX_LBP_HR" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "TSP_PRFST"
------------------------------------------------
 CREATE TABLE "TSP_PRFST" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(30), "POOL_ASYNC_DATA_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "PCT_DATA_PFTCH" DECIMAL(5,2), "POOL_ASYNC_INDEX_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "PCT_INDEX_PFTCH" DECIMAL(5,2), "POOL_ASYNC_COL_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "PCT_COL_PFTCH" DECIMAL(5,2), "PREFETCH_WAIT_TIME" BIGINT , "PREFETCH_WAITS" BIGINT , "UNREAD_PREFETCH_PAGES" BIGINT);
------------------------------------------------
-- DDL Statements for Table "TSP_IOST"
------------------------------------------------
 CREATE TABLE "TSP_IOST" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(30), "VECTORED_IOS" BIGINT , "PAGES_FROM_VECTORED_IOS" BIGINT , "AVG_VIO_SZ" DECIMAL(5,2), "BLOCK_IOS" BIGINT , "PAGES_FROM_BLOCK_IOS" BIGINT , "AVG_BIO_SZ" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "BPL_SIZES"
------------------------------------------------
 CREATE TABLE "BPL_SIZES" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "PAGESIZE" INTEGER NOT NULL, "NUM_PAGES" BIGINT , "SIZE_MB" DECIMAL(10,2), "AUTOMATIC" SMALLINT);
------------------------------------------------
-- DDL Statements for Table "BPL_HITRA"
------------------------------------------------
 CREATE TABLE "BPL_HITRA" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "ROW_DATA_LBP_HITRATIO" DECIMAL(13,2), "COL_DATA_LBP_HITRATIO" DECIMAL(13,2), "INDEX_LBP_HITRATIO" DECIMAL(13,2));
------------------------------------------------
-- DDL Statements for Table "BPL_READS"
------------------------------------------------
 CREATE TABLE "BPL_READS" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT , "POOL_READ_TIME" BIGINT , "AVG_READ_TIME" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "BPL_RDSYNC"
------------------------------------------------
 CREATE TABLE "BPL_RDSYNC" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "POOL_SYNC_DATA_READS" BIGINT , "POOL_SYNC_INDEX_READS" BIGINT , "POOL_SYNC_COL_READS" BIGINT , "POOL_SYNC_READ_TIME" BIGINT , "AVG_SYNC_READ_TIME" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "BPL_RDASYNC"
------------------------------------------------
 CREATE TABLE "BPL_RDASYNC" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "POOL_ASYNC_DATA_READS" BIGINT , "POOL_ASYNC_INDEX_READS" BIGINT , "POOL_ASYNC_COL_READS" BIGINT , "POOL_ASYNC_READ_TIME" BIGINT , "AVG_ASYNC_READ_TIME" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "BPL_WRITE"
------------------------------------------------
 CREATE TABLE "BPL_WRITE" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "POOL_DATA_WRITES" BIGINT , "POOL_INDEX_WRITES" BIGINT , "POOL_XDA_WRITES" BIGINT , "POOL_COL_WRITES" BIGINT , "POOL_WRITE_TIME" BIGINT , "AVG_WRITE_TIME" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "BPL_WRSYNC"
------------------------------------------------
 CREATE TABLE "BPL_WRSYNC" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "POOL_SYNC_DATA_WRITES" BIGINT , "POOL_SYNC_INDEX_WRITES" BIGINT , "POOL_SYNC_XDA_WRITES" BIGINT , "POOL_SYNC_COL_WRITES" BIGINT , "POOL_SYNC_WRITE_TIME" BIGINT , "AVG_WRITE_TIME" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "BPL_WRASYNC"
------------------------------------------------
 CREATE TABLE "BPL_WRASYNC" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "POOL_ASYNC_DATA_WRITES" BIGINT , "POOL_ASYNC_INDEX_WRITES" BIGINT , "POOL_ASYNC_XDA_WRITES" BIGINT , "POOL_ASYNC_COL_WRITES" BIGINT , "POOL_ASYNC_WRITE_TIME" BIGINT , "AVG_WRITE_TIME" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "CON_WAITT"
------------------------------------------------
 CREATE TABLE "CON_WAITT" ("MEMBER" SMALLINT , "APP_NAME" VARCHAR(20), "CLIENT_NAME" VARCHAR(20), "HANDLE" INTEGER , "IDLE_RQ_RATIO" DECIMAL(10,2), "PCT_RQST_WT" DECIMAL(5,2), "PCT_LOCK" DECIMAL(5,2), "PCT_LG_DSK" DECIMAL(5,2), "PCT_LG_BUF" DECIMAL(5,2), "PCT_GLB_LOCK" DECIMAL(5,2), "PCT_LTCH" DECIMAL(5,2), "PCT_RCLM" DECIMAL(5,2), "PCT_CF" DECIMAL(5,2), "PCT_PFTCH" DECIMAL(5,2), "PCT_DIAG" DECIMAL(5,2), "PCT_AUD_W" DECIMAL(5,2), "PCT_AUD_SS" DECIMAL(5,2), "PCT_EVMON" DECIMAL(5,2), "PCT_COMMEXIT" DECIMAL(5,2), "PCT_LOB_PFTCH" DECIMAL(5,2), "PCT_EXTBL" DECIMAL(5,2), "PCT_FED" DECIMAL(5,2), "PCT_POOL_R" DECIMAL(5,2), "PCT_DIR_R" DECIMAL(5,2), "PCT_DIR_W" DECIMAL(5,2), "PCT_FCM" DECIMAL(5,2), "PCT_IDA" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "CON_STATS"
------------------------------------------------
 CREATE TABLE "CON_STATS" ("MEMBER" SMALLINT , "APP_NAME" VARCHAR(20), "CLIENT_NAME" VARCHAR(20), "HANDLE" INTEGER , "TOTAL_APP_COMMITS" BIGINT , "TOTAL_APP_ROLLBACKS" BIGINT , "DEADLOCKS" BIGINT , "ROWS_MODIFIED" BIGINT , "ROWS_READ" BIGINT , "ROWS_RETURNED" BIGINT , "TOTAL_SORTS" BIGINT , "REUSE_STATUS" SMALLINT , "REUSABILITY_STATUS_REASON" VARCHAR(32));
------------------------------------------------
-- DDL Statements for Table "CON_PAGRW"
------------------------------------------------
 CREATE TABLE "CON_PAGRW" ("MEMBER" SMALLINT , "APP_NAME" VARCHAR(20), "CLIENT_NAME" VARCHAR(20), "HANDLE" INTEGER , "TOTAL_APP_COMMITS" BIGINT , "TOTAL_APP_ROLLBACKS" BIGINT , "POOL_DATA_L_READS" BIGINT , "POOL_DATA_P_READS" BIGINT , "POOL_INDEX_L_READS" BIGINT , "POOL_INDEX_P_READS" BIGINT , "POOL_COL_L_READS" BIGINT , "POOL_COL_P_READS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "WLB_SLIST"
------------------------------------------------
 CREATE TABLE "WLB_SLIST" ("MEMBER" SMALLINT , "CACHED_TIMESTAMP" TIMESTAMP , "HOSTNAME" VARCHAR(20), "PORT_NUMBER" INTEGER , "SSL_PORT_NUMBER" INTEGER , "PRIORITY" SMALLINT);
------------------------------------------------
-- DDL Statements for Table "CFG_REGVA"
------------------------------------------------
 CREATE TABLE "CFG_REGVA" ("MEMBER" SMALLINT , "REG_VAR_NAME" VARCHAR(50), "REG_VAR_VALUE" VARCHAR(50), "LEVEL" CHAR(1));
------------------------------------------------
-- DDL Statements for Table "CFG_DB"
------------------------------------------------
 CREATE TABLE "CFG_DB" ("MEMBER" SMALLINT , "NAME" VARCHAR(24), "FLAGS" VARCHAR(10), "CURRENT_VALUE" VARCHAR(64));
------------------------------------------------
-- DDL Statements for Table "CFG_DBM"
------------------------------------------------
 CREATE TABLE "CFG_DBM" ("NAME" VARCHAR(24), "FLAGS" VARCHAR(10), "CURRENT_VALUE" VARCHAR(64));
------------------------------------------------
-- DDL Statements for Table "INS_INFO"
------------------------------------------------
 CREATE TABLE "INS_INFO" ("INST_NAME" VARCHAR(20), "NUM_DBPARTITIONS" INTEGER , "NUM_MEMBERS" INTEGER , "SERVICE_LEVEL" VARCHAR(20), "BLD_LEVEL" VARCHAR(40), "PTF" VARCHAR(40));
------------------------------------------------
-- DDL Statements for Table "DB_MEMST"
------------------------------------------------
 CREATE TABLE "DB_MEMST" ("MEMBER" SMALLINT , "SET_TYPE" VARCHAR(20), "DBNAME" VARCHAR(20), "MEMORY_SET_USED_MB" DECIMAL(10,2), "MEMORY_SET_USED_HWM_MB" DECIMAL(10,2));
------------------------------------------------
-- DDL Statements for Table "DB_MEMPL"
------------------------------------------------
 CREATE TABLE "DB_MEMPL" ("MEMBER" SMALLINT , "MEMORY_POOL_TYPE" VARCHAR(20), "DB_NAME" VARCHAR(20), "MEMORY_POOL_USED_MB" DECIMAL(10,2), "MEMORY_POOL_USED_HWM_MB" DECIMAL(10,2));
------------------------------------------------
-- DDL Statements for Table "CF_GBPIO"
------------------------------------------------
 CREATE TABLE "CF_GBPIO" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(20), "DATA_GBP_HITRATIO" DECIMAL(5,2), "DATA_LBP_HITRATIO" DECIMAL(5,2), "PCT_DATA_INVALID" DECIMAL(5,2), "INDEX_GBP_HITRATIO" DECIMAL(5,2), "INDEX_LBP_HITRATIO" DECIMAL(5,2), "PCT_INDEX_INVALID" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "CF_GBPHR"
------------------------------------------------
 CREATE TABLE "CF_GBPHR" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "POOL_DATA_GBP_L_READS" BIGINT , "POOL_DATA_GBP_P_READS" BIGINT , "DATA_GBP_HITRATIO" DECIMAL(5,2), "POOL_INDEX_GBP_L_READS" BIGINT , "POOL_INDEX_GBP_P_READS" BIGINT , "INDEX_GBP_HITRATIO" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "CF_GBPIV"
------------------------------------------------
 CREATE TABLE "CF_GBPIV" ("MEMBER" SMALLINT , "BP_NAME" VARCHAR(20), "PCT_DATA_GBP_INVALID" DECIMAL(5,2), "PCT_INDEX_GBP_INVALID" DECIMAL(5,2));
------------------------------------------------
-- DDL Statements for Table "CF_GBPDP"
------------------------------------------------
 CREATE TABLE "CF_GBPDP" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(30), "POOL_ASYNC_DATA_GBP_L_READS" BIGINT , "POOL_ASYNC_DATA_GBP_P_READS" BIGINT , "POOL_ASYNC_DATA_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_DATA_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT);
------------------------------------------------
-- DDL Statements for Table "CF_GBPIP"
------------------------------------------------
 CREATE TABLE "CF_GBPIP" ("MEMBER" SMALLINT , "TBSP_NAME" VARCHAR(30), "POOL_ASYNC_INDEX_GBP_L_READS" BIGINT , "POOL_ASYNC_INDEX_GBP_P_READS" BIGINT , "POOL_ASYNC_INDEX_LBP_PAGES_FOUND" BIGINT , "POOL_ASYNC_INDEX_GBP_INVALID_PAGES" BIGINT , "POOL_ASYNC_INDEX_GBP_INDEP_PAGES_FOUND_IN_LBP" BIGINT);
------------------------------------------------
-- DDL Statements for Table "CF_GBPFL"
------------------------------------------------
 CREATE TABLE "CF_GBPFL" ("MEMBER" SMALLINT , "NUM_GBP_FULL" BIGINT);
------------------------------------------------
-- DDL Statements for Table "PAG_RCM"
------------------------------------------------
 CREATE TABLE "PAG_RCM" ("MEMBER" SMALLINT , "TABSCHEMA" VARCHAR(20), "TABNAME" VARCHAR(40), "OBJTYPE" VARCHAR(10), "DATA_PART_ID" INTEGER , "IID" SMALLINT , "PAGE_RECLAIMS" BIGINT , "RECLAIM_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "PAG_RCSMP"
------------------------------------------------
 CREATE TABLE "PAG_RCSMP" ("MEMBER" SMALLINT , "TABSCHEMA" VARCHAR(20), "TABNAME" VARCHAR(40), "OBJTYPE" VARCHAR(10), "DATA_PART_ID" INTEGER , "IID" SMALLINT , "SMP_PAGE_RECLAIMS" BIGINT , "SMP_PAGE_RECLAIM_WAIT_TIME" BIGINT);
------------------------------------------------
-- DDL Statements for Table "CF_RTTIM"
------------------------------------------------
 CREATE TABLE "CF_RTTIM" ("MEMBER" SMALLINT , "ID" SMALLINT , "CF_CMD_NAME" VARCHAR(30), "TOTAL_CF_REQUESTS" BIGINT , "AVG_CF_REQUEST_TIME_MICRO" DECIMAL(15,2));
------------------------------------------------
-- DDL Statements for Table "CF_CMDCT"
------------------------------------------------
 CREATE TABLE "CF_CMDCT" ("MEMBER" SMALLINT , "ID" SMALLINT , "TOTAL_CF_REQUESTS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "CF_CMDTM"
------------------------------------------------
 CREATE TABLE "CF_CMDTM" ("ID" SMALLINT , "CF_CMD_NAME" VARCHAR(50), "TOTAL_CF_REQUESTS" BIGINT , "PCT_TOTAL_CF_CMD" DECIMAL(5,2), "AVG_CF_REQUEST_TIME_MICRO" DECIMAL(15,2));
------------------------------------------------
-- DDL Statements for Table "CF_CMDTO"
------------------------------------------------
 CREATE TABLE "CF_CMDTO" ("ID" SMALLINT , "TOTAL_CF_REQUESTS" BIGINT);
------------------------------------------------
-- DDL Statements for Table "CF_SYSRE"
------------------------------------------------
 CREATE TABLE "CF_SYSRE" ("ID" SMALLINT , "NAME" VARCHAR(30), "VALUE" VARCHAR(50), "UNIT" VARCHAR(10));
------------------------------------------------
-- DDL Statements for Table "CF_SIZE"
------------------------------------------------
 CREATE TABLE "CF_SIZE" ("ID" SMALLINT , "HOSTNAME" VARCHAR(40), "CURR_MEM_MB" DECIMAL(10,2), "CONF_MEM_MB" DECIMAL(10,2), "CURR_GBP_MB" DECIMAL(10,2), "CONF_GBP_MB" DECIMAL(10,2), "TRGT_GBP_MB" DECIMAL(10,2), "CURR_LOCK_MB" DECIMAL(10,2), "CONF_LOCK_MB" DECIMAL(10,2), "TRGT_LOCK_MB" DECIMAL(10,2), "CURR_SCA_MB" DECIMAL(10,2), "CONF_SCA_MB" DECIMAL(10,2), "TRGT_SCA_MB" DECIMAL(10,2));
------------------------------------------------
-- DDL Statements for Table "BLU_PAGDI"
------------------------------------------------
 CREATE TABLE "BLU_PAGDI" ("MEMBER" SMALLINT , "TOTAL_PEDS" BIGINT , "POST_THRESHOLD_PEDS" BIGINT , "DISABLED_PEDS" BIGINT , "TOTAL_PEAS" BIGINT , "POST_THRESHOLD_PEAS" BIGINT);
