/*MONITOR_START_TIME*/select current timestamp as monitor_start_time from sysibm.sysdummy1;
/*DB_GET_CFG_START*/select current timestamp as ts,member, name, value, value_flags from table (db_get_cfg( -2) );
/*DBMCFG_START*/select current timestamp as ts,name, value, value_flags from sysibmadm.dbmcfg;
/*ENV_CF_SYS_RESOURCES_START*/select current timestamp as ts,id, name, value, unit from sysibmadm.env_cf_sys_resources;
/*ENV_GET_REG_VARIABLES_START*/select current timestamp as ts,member, reg_var_name, reg_var_value, level from table (env_get_reg_variables( -2) );
/*ENV_GET_SYSTEM_RESOURCES_START*/select current timestamp as ts,member, os_name, host_name, os_version, os_release, cpu_total, cpu_online, cpu_configured, cpu_speed, cpu_hmt_degree, memory_total, memory_free, cpu_load_short, cpu_load_medium, cpu_load_long, cpu_usage_total, swap_pages_in, swap_pages_out from table (sysproc.env_get_system_resources( ) );
/*ENV_INST_INFO_START*/select current timestamp as ts,inst_name, num_dbpartitions, service_level, bld_level, ptf, num_members from sysibmadm.env_inst_info;
/*MON_GET_BUFFERPOOL_START*/select current timestamp as ts,member, bp_name, bp_cur_buffsz, automatic, pool_read_time, pool_data_l_reads, pool_data_p_reads, pool_async_read_time, pool_async_data_reads, pool_async_index_reads, pool_async_xda_reads, pool_data_writes, pool_async_data_writes, pool_data_lbp_pages_found, pool_async_data_lbp_pages_found, pool_temp_data_l_reads, pool_temp_data_p_reads, pool_index_lbp_pages_found, pool_async_index_lbp_pages_found, pool_temp_index_l_reads, pool_temp_index_p_reads, pool_write_time, pool_async_write_time, pool_index_l_reads, pool_index_p_reads, pool_index_writes, pool_async_index_writes, pool_xda_l_reads, pool_temp_xda_l_reads, pool_xda_p_reads, pool_temp_xda_p_reads, pool_xda_writes, pool_async_xda_writes, pool_data_gbp_l_reads, pool_data_gbp_p_reads, pool_index_gbp_l_reads, pool_index_gbp_p_reads, pool_data_gbp_invalid_pages, pool_async_data_gbp_invalid_pages, pool_index_gbp_invalid_pages, pool_async_index_gbp_invalid_pages, pool_col_l_reads, pool_col_p_reads, pool_async_col_reads, pool_col_writes, pool_async_col_writes, pool_col_lbp_pages_found, pool_async_col_lbp_pages_found, pool_temp_col_l_reads, pool_temp_col_p_reads,b.pagesize from table (mon_get_bufferpool( null, -2) ) mgb,syscat.bufferpools b where trim(b.bpname) = trim(mgb.bp_name);
/*MON_GET_CF_START*/select current timestamp as ts,id, host_name, current_cf_mem_size, configured_cf_mem_size, current_cf_gbp_size, configured_cf_gbp_size, target_cf_gbp_size, current_cf_lock_size, configured_cf_lock_size, target_cf_lock_size, current_cf_sca_size, configured_cf_sca_size, target_cf_sca_size from table (mon_get_cf( null) );
/*MON_GET_CF_CMD_START*/select current timestamp as ts,hostname, id, cf_cmd_name, total_cf_requests, total_cf_cmd_time_micro from table (mon_get_cf_cmd( null) );
/*MON_GET_CF_WAIT_TIME_START*/select current timestamp as ts,member, hostname, id, cf_cmd_name, total_cf_requests, total_cf_wait_time_micro from table (mon_get_cf_wait_time( -2) );
/*MON_GET_CONNECTION_START*/select current timestamp as ts,member, application_name, application_handle, client_applname, connection_reusability_status, reusability_status_reason, client_idle_wait_time, total_rqst_time, rqsts_completed_total, total_wait_time, lock_wait_time, log_disk_wait_time, fcm_recv_wait_time, fcm_send_wait_time, pool_write_time, pool_read_time, direct_write_time, direct_read_time, total_section_sort_time, total_commit_time, total_runstats_time, total_reorg_time, total_load_time, total_app_commits, total_app_rollbacks, deadlocks, rows_modified, rows_read, rows_returned, total_sorts, total_reorgs, total_loads, total_runstats, pool_data_l_reads, pool_data_p_reads, pool_index_l_reads, pool_index_p_reads, ida_send_wait_time, ida_recv_wait_time, cf_wait_time, reclaim_wait_time, total_extended_latch_wait_time, prefetch_wait_time, diaglog_write_wait_time, log_buffer_wait_time, audit_file_write_wait_time, audit_subsystem_wait_time, fcm_message_recv_wait_time, fcm_message_send_wait_time, fcm_tq_recv_wait_time, fcm_tq_send_wait_time, evmon_wait_time, lock_wait_time_global, pool_col_l_reads, pool_col_p_reads, comm_exit_wait_time, ext_table_recv_wait_time, ext_table_send_wait_time, lob_prefetch_wait_time, fed_wait_time from table (mon_get_connection( null, -2) );
/*MON_GET_EXTENDED_LATCH_WAIT_START*/select current timestamp as ts,member, latch_name, total_extended_latch_wait_time, total_extended_latch_waits from table (mon_get_extended_latch_wait( -2) );
/*MON_GET_GROUP_BUFFERPOOL_START*/select current timestamp as ts,member, num_gbp_full from table (mon_get_group_bufferpool( -2) );
/*MON_GET_INDEX_START*/select current timestamp as ts,member, tabschema, tabname, iid, data_partition_id, nleaf, nlevels, index_scans, index_only_scans, key_updates, include_col_updates, pseudo_deletes, del_keys_cleaned, root_node_splits, int_node_splits, boundary_leaf_node_splits, nonboundary_leaf_node_splits, page_allocations, pseudo_empty_pages, empty_pages_reused, empty_pages_deleted, pages_merged, object_index_l_reads, object_index_p_reads, object_index_gbp_l_reads, object_index_gbp_p_reads, object_index_gbp_invalid_pages, object_index_lbp_pages_found, object_index_gbp_indep_pages_found_in_lbp, index_jump_scans from table (mon_get_index( null, null, -2) );
/*MON_GET_MEMORY_POOL_START*/select current timestamp as ts,member, memory_pool_type, db_name, memory_pool_used, memory_pool_used_hwm from table (mon_get_memory_pool( 'database', null, -2) );
/*MON_GET_MEMORY_SET_START*/select current timestamp as ts,member, memory_set_type, db_name, memory_set_used, memory_set_used_hwm from table (mon_get_memory_set( null, null, -2) );
/*MON_GET_PAGE_ACCESS_INFO_START*/select current timestamp as ts,member, tabschema, tabname, objtype, data_partition_id, iid, page_reclaims_x, page_reclaims_s, reclaim_wait_time, spacemappage_page_reclaims_x, spacemappage_page_reclaims_s, spacemappage_reclaim_wait_time from table (mon_get_page_access_info( null, null, -2) );
/*MON_GET_PKG_CACHE_STMT_START*/SELECT CURRENT TIMESTAMP AS TS,MEMBER, PLANID, HEX(EXECUTABLE_ID) EXECUTABLE_ID, PACKAGE_NAME, STMT_TEXT, EFFECTIVE_ISOLATION, STMTID, SEMANTIC_ENV_ID, ACTIVE_SORTS_TOP, SORT_HEAP_TOP, SORT_SHRHEAP_TOP, NUM_EXEC_WITH_METRICS, COORD_STMT_EXEC_TIME, TOTAL_ACT_TIME, TOTAL_CPU_TIME, TOTAL_ACT_WAIT_TIME, LOCK_WAIT_TIME, LOG_DISK_WAIT_TIME, LOG_BUFFER_WAIT_TIME, POOL_WRITE_TIME, POOL_READ_TIME, DIRECT_WRITE_TIME, DIRECT_READ_TIME, ROWS_MODIFIED, ROWS_READ, ROWS_RETURNED, TOTAL_SORTS, SORT_OVERFLOWS, TOTAL_SECTION_TIME, TOTAL_SECTION_SORT_TIME, POOL_DATA_L_READS, POOL_INDEX_L_READS, POOL_DATA_P_READS, POOL_INDEX_P_READS, POOL_DATA_WRITES, POOL_INDEX_WRITES, POOL_TEMP_DATA_P_READS, POOL_TEMP_INDEX_P_READS, DIRECT_READ_REQS, DIRECT_WRITE_REQS, IDA_SEND_WAIT_TIME, IDA_RECV_WAIT_TIME, CF_WAIT_TIME, RECLAIM_WAIT_TIME, TOTAL_EXTENDED_LATCH_WAIT_TIME, LOCK_WAIT_TIME_GLOBAL, PREFETCH_WAIT_TIME, DIAGLOG_WRITE_WAIT_TIME, AUDIT_FILE_WRITE_WAIT_TIME, AUDIT_SUBSYSTEM_WAIT_TIME, FCM_RECV_WAIT_TIME, FCM_SEND_WAIT_TIME, FCM_MESSAGE_RECV_WAIT_TIME, FCM_MESSAGE_SEND_WAIT_TIME, FCM_TQ_RECV_WAIT_TIME, FCM_TQ_SEND_WAIT_TIME, EVMON_WAIT_TIME, POOL_COL_L_READS, POOL_COL_P_READS, TOTAL_COL_TIME, COMM_EXIT_WAIT_TIME, COL_SYNOPSIS_ROWS_INSERTED, EXT_TABLE_RECV_WAIT_TIME, EXT_TABLE_SEND_WAIT_TIME, LOB_PREFETCH_WAIT_TIME, FED_WAIT_TIME FROM TABLE (MON_GET_PKG_CACHE_STMT( NULL, NULL, NULL, -2) ) WHERE STMT_TEXT NOT LIKE 'CALL DBMS_ALERT.SLEEP%' AND STMT_TEXT NOT LIKE '%/* DB2MON */%';
/*MON_GET_SERVERLIST_START*/select current timestamp as ts,member, cached_timestamp, hostname, port_number, ssl_port_number, priority from table (mon_get_serverlist( -2) );
/*MON_GET_TABLE_START*/select current timestamp as ts,member, tabname, tabschema, data_partition_id, tbsp_id, tab_file_id, data_sharing_state_change_time, data_sharing_state, rows_read, rows_inserted, rows_updated, rows_deleted, overflow_accesses, overflow_creates, page_reorgs, direct_read_reqs, direct_write_reqs, object_data_p_reads, object_data_l_reads, data_sharing_remote_lockwait_count, data_sharing_remote_lockwait_time, col_object_l_pages from table (mon_get_table( null, null, -2) );
/*MON_GET_TABLESPACE_START*/select current timestamp as ts,member, tbsp_name, tbsp_page_size, tbsp_id, tbsp_extent_size, tbsp_prefetch_size, fs_caching, pool_read_time, pool_async_read_time, pool_write_time, pool_async_write_time, pool_data_writes, pool_async_data_writes, pool_index_writes, pool_async_index_writes, pool_data_l_reads, pool_temp_data_l_reads, pool_async_data_reads, pool_data_p_reads, pool_temp_data_p_reads, pool_async_index_reads, pool_index_l_reads, pool_temp_index_l_reads, pool_index_p_reads, pool_temp_index_p_reads, pool_xda_l_reads, pool_temp_xda_l_reads, pool_async_xda_reads, pool_xda_p_reads, pool_temp_xda_p_reads, pool_xda_writes, pool_async_xda_writes, unread_prefetch_pages, vectored_ios, pages_from_vectored_ios, block_ios, pages_from_block_ios, pool_data_lbp_pages_found, pool_index_lbp_pages_found, pool_async_data_lbp_pages_found, pool_async_index_lbp_pages_found, direct_read_reqs, direct_write_reqs, direct_read_time, direct_write_time, tbsp_used_pages, tbsp_page_top, pool_data_gbp_l_reads, pool_data_gbp_p_reads, pool_index_gbp_l_reads, pool_index_gbp_p_reads, pool_data_gbp_invalid_pages, pool_async_data_gbp_invalid_pages, pool_index_gbp_invalid_pages, pool_async_index_gbp_invalid_pages, pool_async_data_gbp_l_reads, pool_async_data_gbp_p_reads, pool_async_data_gbp_indep_pages_found_in_lbp, pool_async_index_gbp_l_reads, pool_async_index_gbp_p_reads, pool_async_index_gbp_indep_pages_found_in_lbp, prefetch_wait_time, prefetch_waits, skipped_prefetch_data_p_reads, skipped_prefetch_index_p_reads, skipped_prefetch_temp_data_p_reads, skipped_prefetch_temp_index_p_reads, pool_col_l_reads, pool_col_p_reads, pool_async_col_reads, pool_col_writes, pool_async_col_writes, pool_col_lbp_pages_found, pool_async_col_lbp_pages_found, pool_temp_col_l_reads, pool_temp_col_p_reads from table (mon_get_tablespace( null, -2) ) where tbsp_used_pages > 1000;
/*MON_GET_TRANSACTION_LOG_START*/select current timestamp as ts,member, log_writes, log_write_time, num_log_write_io, num_log_part_page_io, num_log_buffer_full, log_reads, log_read_time, num_log_read_io, log_hadr_wait_time, log_hadr_waits_total, num_log_data_found_in_buffer, cur_commit_log_buff_log_reads, cur_commit_disk_log_reads from table (mon_get_transaction_log( -2) );
/*MON_GET_UTILITY_START*/select current timestamp as ts,member, coord_member, application_handle, utility_start_time, utility_type, utility_operation_type, utility_detail from table (mon_get_utility( -2) );
/*MON_GET_WORKLOAD_START*/select current timestamp as ts,member, workload_name, sort_shrheap_allocated, act_completed_total, total_act_time, total_rqst_time, total_wait_time, lock_wait_time, log_disk_wait_time, pool_write_time, pool_read_time, direct_write_time, direct_read_time, tcpip_recv_wait_time, tcpip_send_wait_time, fcm_recv_wait_time, fcm_send_wait_time, total_cpu_time, total_compile_time, total_compile_proc_time, total_routine_time, total_section_sort_time, total_section_sort_proc_time, total_section_time, total_section_proc_time, total_commit_time, total_rollback_time, total_runstats_time, total_reorg_time, total_load_time, total_app_commits, total_app_rollbacks, deadlocks, lock_timeouts, lock_escals, client_idle_wait_time, rows_modified, rows_read, rows_returned, pkg_cache_inserts, total_sorts, sort_overflows, post_threshold_sorts, post_shrthreshold_sorts, total_reorgs, total_loads, total_runstats, pool_data_l_reads, pool_data_p_reads, pool_temp_data_p_reads, pool_index_l_reads, pool_index_p_reads, pool_temp_index_p_reads, pool_xda_p_reads, pool_temp_xda_p_reads, ida_send_wait_time, ida_recv_wait_time, lock_wait_time_global, total_extended_latch_wait_time, reclaim_wait_time, cf_wait_time, prefetch_wait_time, log_buffer_wait_time, lock_timeouts_global, lock_escals_maxlocks, lock_escals_locklist, lock_escals_global, total_routine_user_code_time, diaglog_write_wait_time, total_connect_request_time, total_connect_request_proc_time, audit_file_write_wait_time, audit_subsystem_wait_time, fcm_message_recv_wait_time, fcm_message_send_wait_time, fcm_tq_recv_wait_time, fcm_tq_send_wait_time, evmon_wait_time, select_sql_stmts, uid_sql_stmts, rows_inserted, rows_updated, total_col_time, total_col_proc_time, total_backup_time, total_index_build_time, total_hash_joins, hash_join_overflows, post_threshold_hash_joins, post_shrthreshold_hash_joins, total_peds, post_threshold_peds, disabled_peds, total_peas, post_threshold_peas, pool_col_l_reads, pool_col_p_reads, pool_temp_col_p_reads, comm_exit_wait_time, total_col_synopsis_time, ext_table_recv_wait_time, ext_table_recvs_total, ext_table_recv_volume, ext_table_read_volume, ext_table_send_wait_time, ext_table_sends_total, ext_table_send_volume, ext_table_write_volume, lob_prefetch_wait_time, fed_wait_time from table (mon_get_workload( null, -2) );
/*MON_CURRENT_SQL_PLUS_START*/ WITH /* DB2MON */
  mga ( ts, count,
coord_member,application_handle,uow_id,activity_id, EXECUTABLE_ID,package_name,section_number,active_sorts,active_sorts_top,active_sort_consumers,active_sort_consumers_top,sort_shrheap_allocated,sort_shrheap_top,post_threshold_sorts,post_shrthreshold_sorts,post_threshold_hash_joins,post_shrthreshold_hash_joins,post_threshold_hash_grpbys,post_threshold_olap_funcs,total_act_time,total_act_wait_time,lock_wait_time,pool_read_time,direct_read_time,direct_write_time,fcm_recv_wait_time,fcm_send_wait_time,total_extended_latch_wait_time,log_disk_wait_time,cf_wait_time,reclaim_wait_time,spacemappage_reclaim_wait_time) as (
    select current timestamp, count(*),       coord_member,application_handle,uow_id,activity_id,
      min(HEX(EXECUTABLE_ID)),min(package_name),min(section_number),
      sum(active_sorts),sum(active_sorts_top),sum(active_sort_consumers),sum(active_sort_consumers_top),sum(sort_shrheap_allocated),sum(sort_shrheap_top),sum(post_threshold_sorts),sum(post_shrthreshold_sorts),sum(post_threshold_hash_joins),sum(post_shrthreshold_hash_joins),sum(post_threshold_hash_grpbys),sum(post_threshold_olap_funcs),sum(total_act_time),sum(total_act_wait_time),sum(lock_wait_time),sum(pool_read_time),sum(direct_read_time),sum(direct_write_time),sum(fcm_recv_wait_time),sum(fcm_send_wait_time),sum(total_extended_latch_wait_time),sum(log_disk_wait_time),sum(cf_wait_time),sum(reclaim_wait_time),sum(spacemappage_reclaim_wait_time) 
    from table(mon_get_activity(null,-2))
    group by coord_member,application_handle,uow_id,activity_id)
select ts, count,mcs.coord_member,mcs.application_handle,mcs.uow_id,mcs.activity_id,mcs.elapsed_time_sec,mcs.total_cpu_time,mcs.rows_read,mcs.direct_reads,mcs.direct_writes,mga.executable_id,mga.package_name,mga.section_number,mga.active_sorts,mga.active_sorts_top,mga.active_sort_consumers,mga.active_sort_consumers_top,mga.sort_shrheap_allocated,mga.sort_shrheap_top,mga.post_threshold_sorts,mga.post_shrthreshold_sorts,mga.post_threshold_hash_joins,mga.post_shrthreshold_hash_joins,mga.post_threshold_hash_grpbys,mga.post_threshold_olap_funcs,mga.total_act_time,mga.total_act_wait_time,mga.lock_wait_time,mga.pool_read_time,mga.direct_read_time,mga.direct_write_time,mga.fcm_recv_wait_time,mga.fcm_send_wait_time,mga.total_extended_latch_wait_time,mga.log_disk_wait_time,mga.cf_wait_time,mga.reclaim_wait_time,mga.spacemappage_reclaim_wait_time,mcs.stmt_text
from 
  sysibmadm.mon_current_sql mcs, mga 
where 
  mcs.application_handle = mga.application_handle and 
  mcs.coord_member = mga.coord_member and 
  mcs.uow_id = mga.uow_id and 
  mcs.activity_id = mga.activity_id and
  mcs.stmt_text not like '%/* IBM_DB2MON */%'
  with UR;
/*MON_GET_LOCKS_START*/SELECT /* DB2MON */
(select cast(substr(tbspace,1,20) as varchar(20)) from syscat.tablespaces where tbspaceid = tbsp_id) tbspace,
(select cast(substr(tabname,1,30) as varchar(30)) from syscat.tables where tab_file_id = tableid and tbspaceid = tbsp_id) tabname,
  cast(substr(lock_object_type,1,12) as varchar(12)) lock_obj_type,
  lock_name,
  lock_mode,
  lock_status,
  member,
  integer(application_handle) apphdl
from
  table ( mon_get_locks(null,-2) )
where
  lock_name in (select lock_name from table ( mon_get_locks(null,-2) ) where lock_status = 'W')
order by
  lock_object_type, lock_name, lock_status, lock_mode
with UR;
