#!/usr/bin/env bash
# cleanup.sh — destroys all RDS for Db2 Terraform modules in reverse order,
# then optionally resets module directories to a pristine checkout state.
#
# State lives in S3 (configured by configure-modules.sh), so "has state"
# is detected by the presence of backend.tf referencing the remote state.
#
# Usage:
#   AWS_PROFILE=<profile> ./cleanup.sh

set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MODULES=(
  "6-license-manager"
  "5-rds"
  "4-parameter-group"
  "3-kms"
  "2-iam"
  "1-networking"
)

echo "Modules to destroy (in order):"
for m in "${MODULES[@]}"; do echo "  - $m"; done
echo
echo "NOTE:"
echo "  - 5-rds can take 10-20 minutes to delete."
echo "  - 3-kms puts the KMS key in 30-day pending deletion (not fully removed)."
echo "  - 0-backend-setup (state bucket + lock table) is NOT destroyed."
echo "  - If AWS_PROFILE is set (currently '${AWS_PROFILE:-unset}'), it will be used."
echo
read -p "Type 'yes' to confirm destruction: " confirm
[[ "$confirm" != "yes" ]] && { echo "Aborted."; exit 0; }

for module in "${MODULES[@]}"; do
  dir="$SCRIPT_DIR/$module"
  if [[ ! -d "$dir" ]]; then
    echo "Skipping $module (directory not found)"
    continue
  fi
  if [[ ! -f "$dir/backend.tf" ]]; then
    echo "Skipping $module (no backend.tf — module was never configured)"
    continue
  fi

  echo
  echo "=== Destroying $module ==="
  cd "$dir"

  # Ensure provider plugins are present — needed after a fresh checkout
  if [[ ! -d ".terraform" ]]; then
    echo "  Running terraform init..."
    terraform init -input=false -no-color >/dev/null || {
      echo "  terraform init failed for $module — skipping"
      cd "$SCRIPT_DIR"
      continue
    }
  fi

  terraform destroy -auto-approve -no-color || \
    echo "  Warning: destroy had errors in $module (continuing)"
  cd "$SCRIPT_DIR"
done

echo
echo "Destroy complete."
echo
echo "Remaining resources you may want to remove manually:"
echo "  - KMS key (30-day pending deletion — aws kms cancel-key-deletion to recover)"
echo "  - 0-backend-setup state bucket + DynamoDB lock table"
echo "  - Any S3 buckets with create_s3_backup_bucket=false / create_audit_bucket=false"
echo "    that Terraform did NOT manage (they were referenced by ARN only)"

# ── Optional reset: return module dirs to pristine checkout state ────────────

echo
echo "OPTIONAL: Reset module directories for a fresh test run"
echo "This will DELETE from every module (1-6):"
echo "  - .terraform/                (provider plugins — regenerated by 'terraform init')"
echo "  - .terraform.lock.hcl        (provider lock file)"
echo "  - terraform.tfvars           (your values — terraform.tfvars.example is kept)"
echo "  - backend.tf                 (regenerated by ./configure-modules.sh)"
echo "  - terraform.tfstate*         (stale local state files, if any)"
echo "  - crash.log, tfplan*         (leftover plan/debug files)"
echo
echo "0-backend-setup is left alone (state bucket + lock table still exist)."
echo
read -p "Type 'yes' to reset module files, anything else to skip: " reset_confirm
if [[ "$reset_confirm" != "yes" ]]; then
  echo "Reset skipped. Module directories left as-is."
  exit 0
fi

# Modules to reset (everything downstream of 0-backend-setup)
RESET_MODULES=(
  "1-networking"
  "2-iam"
  "3-kms"
  "4-parameter-group"
  "5-rds"
  "6-license-manager"
)

for module in "${RESET_MODULES[@]}"; do
  dir="$SCRIPT_DIR/$module"
  [[ ! -d "$dir" ]] && continue
  echo "Resetting $module..."
  rm -rf "$dir/.terraform"
  rm -f  "$dir/.terraform.lock.hcl"
  rm -f  "$dir/terraform.tfvars"
  rm -f  "$dir/backend.tf"
  rm -f  "$dir/terraform.tfstate" "$dir/terraform.tfstate.backup"
  rm -f  "$dir/crash.log" "$dir/tfplan" "$dir/tfplan.out"
done

echo
echo "Reset complete."
echo

# ── Optional phase 3: also wipe 0-backend-setup caches (not state) ───────────

echo "OPTIONAL: Also clean 0-backend-setup caches (provider plugin + lock file)"
echo "This will DELETE from 0-backend-setup:"
echo "  - .terraform/                (provider plugins — regenerated by 'terraform init')"
echo "  - .terraform.lock.hcl        (provider lock file)"
echo
echo "Kept (you need these to manage the state bucket):"
echo "  - main.tf, variables.tf, outputs.tf  (the module itself)"
echo "  - terraform.tfstate                  (local state for the backend module)"
echo "  - terraform.tfvars / .example        (your bucket name + region)"
echo
read -p "Type 'yes' to clean 0-backend-setup caches, anything else to skip: " bootstrap_reset
if [[ "$bootstrap_reset" == "yes" ]]; then
  dir="$SCRIPT_DIR/0-backend-setup"
  if [[ -d "$dir" ]]; then
    echo "Cleaning 0-backend-setup..."
    rm -rf "$dir/.terraform"
    rm -f  "$dir/.terraform.lock.hcl"
    rm -f  "$dir/.terraform.tfstate.lock.info"
    echo "Done. Run 'terraform init' in 0-backend-setup before reapplying."
  fi
else
  echo "0-backend-setup caches left as-is."
fi

echo
echo "To start a new test:"
echo "  1. cd 0-backend-setup && terraform init && terraform apply"
echo "  2. ./configure-modules.sh                       # regenerate backend.tf for 1-6"
echo "  3. cp 1-networking/terraform.tfvars.example 1-networking/terraform.tfvars"
echo "     ...and edit, then repeat for each module"
